### ISSUE TITLE
Interface to Darwin Notifications

### ISSUE THREAD

**Issue by lawrencelomax** [facebook/idb#202]
There's a few interesting ones that do tasks that `SimulatorBridge` doesnt:
- `com.apple.UIKit.SimulatorShake`
- `com.apple.BiometricKit_Sim.fingerTouch.match`
- `com.apple.BiometricKit_Sim.fingerTouch.nomatch`
- `com.apple.BiometricKit.enrollmentChanged`
- `com.apple.iphonesimulator.toggleincallstatusbar`
- `com.apple.UIKit.SimulatorSlowMotionAnimationState`
- `com.apple.UIKit.ForceGraphicsQuality`
- `com.apple.UIKit.SimulatorSlowMotionStateful`

**Comment by flockoffiles** [comment]
While sending **com.apple.BiometricKit_Sim.fingerTouch.match** and **com.apple.BiometricKit_Sim.fingerTouch.nomatch** produces produces changes in the Simulator, **com.apple.BiometricKit.enrollmentChanged** does not seem to do anything.

By debugging the Simulator application I saw that the Simulator always starts up in the non-enrolled state (which is very inconvenient for tests which require biometric functionality).
When I toggle the enrolled state via Menu (Hardware -> Touch ID -> Enrolled), I see that **com.apple.BiometricKit.enrollmentChanged** IS being sent, but some other action is apparently being done as well...
