### ISSUE TITLE
How can I run my UI tests on multiple simulators

### ISSUE THREAD

**Issue by kumariswarnim** [facebook/idb#336]
Hi Team,

I am using XCode 8 with XCTest framework to write my UI tests in swift and I am unable to identify how can I run my test on multiple simulators. What commands should I be using to run my UI test on 2-3 different simulators. It would be great if you could help me to sort this out asap.

Thanks,
Swarnim

**Comment by lawrencelomax** [comment]
You can use the `launch_xctest` command to do this. The documentation for this is lacking but this should help you out.

```
# Boot and then launch on the first simulator
$ fbsimctl 425F5191-3500-4183-924F-F5229261CD63 boot
$ fbsimctl 425F5191-3500-4183-924F-F5229261CD63 launch_xctest /Path/To/TestBundle.xctest com.apple.Preferences -- listen
# Boot and then launch on the second simulator, with the same test bundle
$ fbsimctl 38A1346B-A5E9-474D-94A6-EF8ADC7933C2 boot
$ fbsimctl 38A1346B-A5E9-474D-94A6-EF8ADC7933C2 launch_xctest /Path/To/TestBundle.xctest com.apple.Preferences -- listen
```

**Comment by kumariswarnim** [comment]
Thank you Lawrence. How can the test bundle? Do I have to export it from xcode?

**Comment by lawrencelomax** [comment]
The Test Bundle can be created from Xcode or `xcodebuild`. All Test Bundles end in `.xctest` and contain the executable code for the test. With a UI Test, the test bundle will typically specify the App-Under-Test to launch. This Application must of course be installed, or the test bundle will be unable to launch the App-Under-Test.

**Comment by kumariswarnim** [comment]
Actually I can see like this in my xcode project structure. I don't know what is the issue.
![screen shot 2016-11-18 at 15 55 15](https://cloud.githubusercontent.com/assets/11741739/20436277/8939574e-ada7-11e6-9526-b2fa3da410d8.png)

**Comment by lawrencelomax** [comment]
Based on naming alone, I expect both of these targets to use the `XCUITest` APIs, if you build any of those targets with 'Build for Testing' you should be able to build the target and use it with the `launch_xctest` target.

**Comment by luisxiaomai** [comment]
@lawrencelomax, I follow above instruction to have a try, but failed with below issue, can you help on this?

`Starting test session with ID 79720252-59B6-4B1B-AE85-E105D4D78856
testmanagerd handled session request using protcol version 22.
Test Completed with Result: Bundle Connection Failed in error: Error Domain=com.facebook.XCTestBootstrap Code=0 "Timeout establishing connection" UserInfo={NSLocalizedDescription=Timeout establishing connection}
Error Domain=com.facebook.FBSimulatorControl Code=0 "Failed start test manager" UserInfo={NSLocalizedDescription=Failed start test manager, NSUnderlyingError=0x7f8c1859d360 {Error Domain=com.facebook.XCTestBootstrap Code=0 "Test Manager Connection Failed: Internal Error Error Domain=com.facebook.XCTestBootstrap Code=0 "Timeout establishing connection" UserInfo={NSLocalizedDescription=Timeout establishing connection}" UserInfo={NSLocalizedDescription=Test Manager Connection Failed: Internal Error Error Domain=com.facebook.XCTestBootstrap Code=0 "Timeout establishing connection" UserInfo={NSLocalizedDescription=Timeout establishing connection}, NSUnderlyingError=0x7f8c1859f2b0 {Error Domain=com.facebook.XCTestBootstrap Code=0 "Timeout establishing connection" UserInfo={NSLocalizedDescription=Timeout establishing connection}}}}}`

**Comment by phoebusliang** [comment]
Hi @lawrencelomax ,
Steps:

1. download newest version of webdriveragent project
2. use fbsimctl to boot and install my app: xx.app
3. execute ./Documents/fbsimctl/fbsimctl --state=booted launch_xctest /Users/name/Documents/workspace/xcode/WebDriverAgent/Build/Products/Debug-iphonesimulator/WebDriverAgentRunner-Runner.app/PlugIns/WebDriverAgentRunner.xctest xxapp --port 8101 -- listen
4. the result of 'step3' in console like below, and xxapp start then run as background

Connection Did Connect => Bridge: Framebuffer ((null)) | HID (null) | (null)
C23B6BE0-EC4A-4560-B00E-E23D64E7C706 | iPhone 7 Plus | Booted | iPhone 7 Plus | iOS 10.0: launch: Bridge: Framebuffer ((null)) | HID (null) | (null)
Application Did Launch => Process xxapp | PID 82610
C23B6BE0-EC4A-4560-B00E-E23D64E7C706 | iPhone 7 Plus | Booted | iPhone 7 Plus | iOS 10.0: launch: Process xxapp | PID 82610
Connecting Test Bundle
Creating the test bundle connection.
Listening for proxy connection request from the test bundle (all platforms)
Resuming the test bundle connection.
Checking test manager availability...
Starting test session with ID EB42A77E-C406-4FC6-8CFE-7B6381AC47F0
testmanagerd handled session request using protcol version 22.
Got proxy channel request from test bundle
Test bundle is ready, running protocol 22, requires at least version 8. IDE is running 22 and requires at least 8
Test Bundle is Ready
Starting the daemon connection
Resuming the daemon connection.
Whitelisting test process ID 82610
Got whitelisting response and daemon protocol version 22
Ready to execute test plan
Bundle Connection scheduling start of Test Plan
Daemon Notified of start of test plan
TestManager Did Connect => TestManager Awaiting Result for (Test Host PID 82610 | Test Host Bundle xxapp | Session ID EB42A77E-C406-4FC6-8CFE-7B6381AC47F0)
Listen Started: empty
Test Plan Started
Started initilizing for UI testing.

5. I access to http://localhost:8101/status, the JSON response is:
{
value: {
state: "success",
os: {
name: "iOS",
version: "10.0"
},
ios: {
simulatorVersion: "10.0"
},
build: {
time: "Nov 26 2016 23:43:05"
}
},
sessionId: "29533E81-24EF-415E-9717-A7EB77E4221B",
status: 0
}

6. when i execute curl -X POST '-H "Content-Type: application/json"' -d "{\"using\":\"class name\",\"value\":\"XCUIElementTypeButton\"}" http://localhost:8101/session/13B27F37-B0F0-4D85-9972-0B36520B33C1/elements

the response(but my app is still running and no log in fbsimctl session.):
{
"value" : "Application is not running, possibly crashed",
"sessionId" : "13B27F37-B0F0-4D85-9972-0B36520B33C1",
"status" : 10
}%

**Comment by kumariswarnim** [comment]
hi @phoebusliang,

I have tried running the above command and it gave me an error saying:

Failed to Parse Command '["--state=booted", "launch_xctest", "/Users/swarnimkumari/Library/Developer/Xcode/DerivedData/Build/Products/Debug-iphonesimulator/WebDriverAgentRunner-Runner.app/PlugIns/WebDriverAgentRunner.xctest xxapp --port 8101 -- listen]' does not match '[fbsimctl {{ [output] | [management] | --set <directory> }}* [targets]? [target-format]* {{ [action] ... -- [action] }}+

**Comment by lawrencelomax** [comment]
@phoebusliang It looks like `WebDriverAgent` has indeed launched fine as indicated by step 5. However, it looks like you are not starting a session for a particular Application. `WebDriverAgent` acts a Endpoint-node and therefore needs to start a session for an Application before anything becomes usable. This is probably why you are seeing an error in step 6. There are more details about how to start a [session on the `WebDriverAgent` Wiki](https://github.com/facebook/WebDriverAgent/wiki/Queries#starting-session-and-launching-application).

@kumariswarnim Does the file at `/Users/swarnimkumari/Library/Developer/Xcode/DerivedData/Build/Products/Debug-iphonesimulator/WebDriverAgentRunner-Runner.app/PlugIns/WebDriverAgentRunner.xctest` exist on your machine? You will get that kind of error if that is the case. The `xxapp` argument that you have should be substituted with the Application you wish to inject into. You can substitute this with `com.apple.Preferences` for example.

**Comment by kumariswarnim** [comment]
Yes @lawrencelomax. The above was just an example but my actual command is:

fbsimctl --state=booted launch_xctest /Users/swarnimkumari/Library/Developer/Xcode/DerivedData/Busuu-cncqkwkictidambqwmqhjxojargw/Build/Products/Test-iphonesimulator/BusuuUITests-Runner.app/PlugIns/BusuuUITests.xctest busuuapp --port 8101 -- listen

**Comment by kumariswarnim** [comment]
I think I made it running. I should use the <Bundle_id>. Thanks @lawrencelomax. But I am getting another issue now.

**Starting test session with ID 6B77065D-4C89-42D9-8094-4F342F477DD4
testmanagerd handled session request using protcol version 22.
Test Completed with Result: Bundle Connection Failed in error: Error Domain=com.facebook.XCTestBootstrap Code=0 "Timeout establishing connection" UserInfo={NSLocalizedDescription=Timeout establishing connection}
Error Domain=com.facebook.FBSimulatorControl Code=0 "Failed start test manager" UserInfo={NSLocalizedDescription=Failed start test manager, NSUnderlyingError=0x7fdefa4afa60 {Error Domain=com.facebook.XCTestBootstrap Code=0 "Test Manager Connection Failed: Internal Error Error Domain=com.facebook.XCTestBootstrap Code=0 "Timeout establishing connection" UserInfo={NSLocalizedDescription=Timeout establishing connection}" UserInfo={NSLocalizedDescription=Test Manager Connection Failed: Internal Error Error Domain=com.facebook.XCTestBootstrap Code=0 "Timeout establishing connection" UserInfo={NSLocalizedDescription=Timeout establishing connection}, NSUnderlyingError=0x7fdefa4afa30 {Error Domain=com.facebook.XCTestBootstrap Code=0 "Timeout establishing connection" UserInfo={NSLocalizedDescription=Timeout establishing connection}}}}}**

**Comment by marekcirkos** [comment]
@kumariswarnim Is it persistent?

**Comment by kumariswarnim** [comment]
Yes @marekcirkos

**Comment by marekcirkos** [comment]
@kumariswarnim This is weird. Can you try using com.apple.Preferences as hosting app?

**Comment by kumariswarnim** [comment]
I am using Xcode 8. When I used "com.apple.Preference then I get this output:

**Busuus-MacBook-Pro-13:~ swarnimkumari$ fbsimctl --state=booted launch_xctest /Users/swarnimkumari/Library/Developer/Xcode/DerivedData/Busuu-cncqkwkictidambqwmqhjxojargw/Build/Products/Debug-iphonesimulator/BusuuUITests-Runner.app/PlugIns/BusuuUITests.xctest com.apple.Preferences --port 8101 -- listen
Connection Did Connect => Bridge: Framebuffer ((null)) | HID (null) | (null)
636831FF-73CF-4E7F-8EB6-6F624BAD669B | iPhone 6 Plus | Booted | iPhone 6 Plus | iOS 10.0: launch: Bridge: Framebuffer ((null)) | HID (null) | (null)
Application Did Launch => Process Preferences | PID 78993
636831FF-73CF-4E7F-8EB6-6F624BAD669B | iPhone 6 Plus | Booted | iPhone 6 Plus | iOS 10.0: launch: Process Preferences | PID 78993
Connecting Test Bundle
Creating the test bundle connection.
Listening for proxy connection request from the test bundle (all platforms)
Resuming the test bundle connection.
Checking test manager availability...
Starting test session with ID 95D2D353-188C-4CCA-BCF9-EE7DDFF39A66
Application Did Terminate => Expected 0 Process Preferences | PID 78993
636831FF-73CF-4E7F-8EB6-6F624BAD669B | iPhone 6 Plus | Booted | iPhone 6 Plus | iOS 10.0: terminate: Process Preferences | PID 78993
testmanagerd handled session request using protcol version 22.
Test Completed with Result: Bundle Connection Failed in error: Error Domain=com.facebook.XCTestBootstrap Code=0 "Timeout establishing connection" UserInfo={NSLocalizedDescription=Timeout establishing connection}
Error Domain=com.facebook.FBSimulatorControl Code=0 "Failed start test manager" UserInfo={NSLocalizedDescription=Failed start test manager, NSUnderlyingError=0x7ff0324adc20 {Error Domain=com.facebook.XCTestBootstrap Code=0 "Test Manager Connection Failed: Internal Error Error Domain=com.facebook.XCTestBootstrap Code=0 "Timeout establishing connection" UserInfo={NSLocalizedDescription=Timeout establishing connection}" UserInfo={NSLocalizedDescription=Test Manager Connection Failed: Internal Error Error Domain=com.facebook.XCTestBootstrap Code=0 "Timeout establishing connection" UserInfo={NSLocalizedDescription=Timeout establishing connection}, NSUnderlyingError=0x7ff0324acb50 {Error Domain=com.facebook.XCTestBootstrap Code=0 "Timeout establishing connection" UserInfo={NSLocalizedDescription=Timeout establishing connection}}}}}**

**Comment by marekcirkos** [comment]
@kumariswarnim I am not sure to be honest. Looks like something is wrong with test bundle. Can you try any other XCUITest bundle?

**Comment by kumariswarnim** [comment]
@marekcirkos It is giving the same error with other XCUITest bundle. Can you please investigate what is the issue?

**Comment by cosminstirbu** [comment]
I have the same issue as @kumariswarnim 
I am trying to run the `.xctest` bundle for a `.framework` - which don't require a host app by default.

If I `pass com.apple.Preferences` as a parameter I receive the same timeout error. If I don't pass the host app I receive a command parsing error.

Is the host app always required by `fbsimctl`? Is there a plan to not require it in the future?

**Comment by marekcirkos** [comment]
@cosminstirbu Host app is required. Sim/device can't execute pure test bundles, so it needs app that will host that test bundle. Apple does exact same thing with UI tests, tho the automatically wrap test bundle into auto-generated application.

**Comment by cosminstirbu** [comment]
@marekcirkos 

I understand.
Unfortunately if a I pass `com.apple.Preferences` for instance, or even a sample app of my own I  also receive the timeout error that @kumariswarnim is seeing.

I have also cloned an build `fbxctest` and I am currently poking around to understand how it can be used. Do you maybe have an usage example of `fbxctest`?

**Comment by jasenhuang** [comment]
@lawrencelomax @phoebusliang Hi guys, i follow all the steps you go, but WebDriverRunner server couldn't be started, any ideas?

command:
./fbsimctl CB4C66F7-FF6E-41CD-A522-6565F06D5C3A  launch_xctest /Users/jasenhuang/Library/Developer/Xcode/DerivedData/WebDriverAgent-gfouxdscsrxhtqavrdmxmosntgsh/Build/Products/Debug-iphonesimulator/WebDriverAgentRunner-Runner.app/PlugIns/WebDriverAgentRunner.xctest com.apple.Preferences --port 8100 --listen

logs:
Application Did Launch => Process Preferences | PID 89739
CB4C66F7-FF6E-41CD-A522-6565F06D5C3A | iPhone 7 Plus | Booted | iPhone 7 Plus | iOS 10.2: launch: Process Preferences | PID 89739
Connecting Test Bundle
Creating the test bundle connection.
Listening for proxy connection request from the test bundle (all platforms)
Resuming the test bundle connection.
Checking test manager availability...
Starting test session with ID 7AFA2388-9B87-4C76-A93C-C82553FEAB2C
testmanagerd handled session request using protcol version 22.
Got proxy channel request from test bundle
Test bundle is ready, running protocol 22, requires at least version 8. IDE is running 22 and requires at least 8
Test Bundle is Ready
Starting the daemon connection
Resuming the daemon connection.
Whitelisting test process ID 89739
Got whitelisting response and daemon protocol version 22
Ready to execute test plan
Bundle Connection scheduling start of Test Plan
Daemon Notified of start of test plan
TestManager Did Connect => TestManager Awaiting Result for (Test Host PID 89739 | Test Host Bundle com.apple.Preferences | Session ID 7AFA2388-9B87-4C76-A93C-C82553FEAB2C)

**Comment by lawrencelomax** [comment]
The reason that the command fails is that the `fbsimctl` process needs to be running in order to maintain an active connection to the test manager daemon. The arguments you are providing will mean the test bundle launches, and then immediately hangs up:

```
fbsimctl CB4C66F7-FF6E-41CD-A522-6565F06D5C3A launch_xctest /Users/jasenhuang/Library/Developer/Xcode/DerivedData/WebDriverAgent-gfouxdscsrxhtqavrdmxmosntgsh/Build/Products/Debug-iphonesimulator/WebDriverAgentRunner-Runner.app/PlugIns/WebDriverAgentRunner.xctest com.apple.Preferences --port 8100 --listen
```

With `--listen` as the last argument, this will be passed to `WebDriverAgent` rather than keeping `fbsimctl` alive. You should use  `-- listen` (with a space after the `--`) instead:

```
fbsimctl CB4C66F7-FF6E-41CD-A522-6565F06D5C3A launch_xctest /Users/jasenhuang/Library/Developer/Xcode/DerivedData/WebDriverAgent-gfouxdscsrxhtqavrdmxmosntgsh/Build/Products/Debug-iphonesimulator/WebDriverAgentRunner-Runner.app/PlugIns/WebDriverAgentRunner.xctest com.apple.Preferences --port 8100 -- listen
```

The other alternative is to [write a script](https://github.com/facebook/FBSimulatorControl/issues/274#issuecomment-282795401) that will avoid the need to separate these arguments manually, since the command line parser has to do the heavy lifting of disambiguating arguments to the Application and to `fbsimctl` itself.

**Comment by jasenhuang** [comment]
thx to @lawrencelomax ,  it works after use -- listen (with a space after the --) instead.  these arguments are really confusing, haha
