### ISSUE TITLE
brew install fbsimctl fails with: Code signing is required for product type 'Command-line Tool' in SDK 'macOS 10.12'

### ISSUE THREAD

**Issue by LeoNatan** [facebook/idb#342]
I am using macOS 10.12.2 beta 3 and Xcode 8.2 beta 3. Running either `brew install fbsimctl` or `brew install fbsimctl --head` fails with the following error:

> ```
> Leo-Natans-Wix-MPB:detox lnatan$ brew install fbsimctl
> ==> Installing fbsimctl from facebook/fb
> ==> Downloading https://github.com/facebook/FBSimulatorControl/tarball/v0.2.2
> ==> Downloading from https://codeload.github.com/facebook/FBSimulatorControl/legacy.tar.gz/v0.2.2
> ######################################################################## 100.0%
> ==> ./build.sh fbsimctl build /usr/local/Cellar/fbsimctl/0.2.2
> Last 15 lines from /Users/lnatan/Library/Logs/Homebrew/fbsimctl/01.build.sh:
>     cd /tmp/fbsimctl-20161130-48922-km8ocr/facebook-FBSimulatorControl-f41dec3/fbsimctl
>     /usr/bin/touch -c /tmp/fbsimctl-20161130-48922-km8ocr/facebook-FBSimulatorControl-f41dec3/build/Build/Products/Debug/FBSimulatorControlKit.framework
> 
> === BUILD TARGET fbsimctl OF PROJECT fbsimctl WITH CONFIGURATION Debug ≡
> 
> Check dependencies
> "fbsimctl" isn't code signed but requires entitlements. It is not possible to add entitlements to a binary without signing it.
> Code signing is required for product type 'Command-line Tool' in SDK 'macOS 10.12'
> 
> ** BUILD FAILED **
> 
> 
> The following build commands failed:
> 	Check dependencies
> (1 failure)
> 
> If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
> https://github.com/facebook/homebrew-fb/issues
> 
> 
> Error: You are using a pre-release version of Xcode.
> You may encounter build failures or other breakages.
> Please create pull-requests instead of filing issues.Leo-Natans-Wix-MPB:detox lnatan$ brew install fbsimctl
> ==> Installing fbsimctl from facebook/fb
> ==> Downloading https://github.com/facebook/FBSimulatorControl/tarball/v0.2.2
> ==> Downloading from https://codeload.github.com/facebook/FBSimulatorControl/legacy.tar.gz/v0.2.2
> ######################################################################## 100.0%
> ==> ./build.sh fbsimctl build /usr/local/Cellar/fbsimctl/0.2.2
> Last 15 lines from /Users/lnatan/Library/Logs/Homebrew/fbsimctl/01.build.sh:
>     cd /tmp/fbsimctl-20161130-48922-km8ocr/facebook-FBSimulatorControl-f41dec3/fbsimctl
>     /usr/bin/touch -c /tmp/fbsimctl-20161130-48922-km8ocr/facebook-FBSimulatorControl-f41dec3/build/Build/Products/Debug/FBSimulatorControlKit.framework
> 
> === BUILD TARGET fbsimctl OF PROJECT fbsimctl WITH CONFIGURATION Debug ≡
> 
> Check dependencies
> "fbsimctl" isn't code signed but requires entitlements. It is not possible to add entitlements to a binary without signing it.
> Code signing is required for product type 'Command-line Tool' in SDK 'macOS 10.12'
> 
> ** BUILD FAILED **
> 
> 
> The following build commands failed:
> 	Check dependencies
> (1 failure)
> 
> If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
> https://github.com/facebook/homebrew-fb/issues
> 
> 
> Error: You are using a pre-release version of Xcode.
> You may encounter build failures or other breakages.
> Please create pull-requests instead of filing issues.
> ```

**Comment by LeoNatan** [comment]
Building the project from Xcode works, but from cmd fails with the error above.

**Comment by LeoNatan** [comment]
Hmm, with Xcode 8.1 this issue does not reproduce. I will open a but report with Apple tomorrow.

**Comment by lawrencelomax** [comment]
@LeoNatan it might also be worth checking in with `homebrew` here. I'm not sure if Apple added a `codesign` requirement for all builds in Xcode 8.2, but it wasn't a requirement for Mac binaries in Xcode 8.0.

Re-open if there's anything that `fbsimctl` needs to do here around codesigning.

**Comment by LeoNatan** [comment]
Thanks
Let's wait for the a newer beta and see. I might also test on a different machine with Xcode 8.2 to see if a special combination of circumstances. Since the project built within Xcode itself, to me it looks like bug in the command line tools.

**Comment by LeoNatan** [comment]
@lawrencelomax Issue persists.

```
brew tap facebook/fb
brew install fbsimctl --HEAD
```

> ==> Installing fbsimctl from facebook/fb
> ==> Cloning https://github.com/facebook/FBSimulatorControl.git
> Updating /Users/lnatan/Library/Caches/Homebrew/fbsimctl--git
> ==> Checking out branch master
> ==> ./build.sh fbsimctl build /usr/local/Cellar/fbsimctl/HEAD-244a622
> Last 15 lines from /Users/lnatan/Library/Logs/Homebrew/fbsimctl/01.build.sh:
>     cd /tmp/fbsimctl-20170118-36571-pwc8nx/fbsimctl
>     /usr/bin/touch -c /tmp/fbsimctl-20170118-36571-pwc8nx/build/Build/Products/Debug/FBSimulatorControlKit.framework
> 
> === BUILD TARGET fbsimctl OF PROJECT fbsimctl WITH CONFIGURATION Debug ≡
> 
> Check dependencies
> "fbsimctl" isn't code signed but requires entitlements. It is not possible to add entitlements to a binary without signing it.
> Code signing is required for product type 'Command-line Tool' in SDK 'macOS 10.12'
> 
> ** BUILD FAILED **
> 
> 
> The following build commands failed:
> 	Check dependencies
> (1 failure)
> 
> If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
> https://github.com/facebook/homebrew-fb/issues

**Comment by LeoNatan** [comment]
This is unrelated to `homebrew`. Building from command line fails with the same error, while building from Xcode succeeds.

**Comment by LeoNatan** [comment]
Using `export CODE_SIGNING_REQUIRED=NO && brew install fbsimctl --HEAD` is a workaround for this issue, however the root cause remains unclear.

**Comment by lawrencelomax** [comment]
I think this is just the case of adding this project setting to the scheme used to build `fbsimctl`.

**Comment by LeoNatan** [comment]
@lawrencelomax Any news on fixing this on your end? More and more people are hitting this. We use fbsimctl as a prerequisite of https://github.com/wix/detox and people with newer Xcode are hitting this issue.

**Comment by kantharia** [comment]
Any solution ?

**Comment by kantharia** [comment]
Any solution?

**Comment by LeoNatan** [comment]
We use `export CODE_SIGNING_REQUIRED=NO && brew install fbsimctl --HEAD` command as a workaround.

**Comment by lekenny** [comment]
it's work !!!

**Comment by spinningarrow** [comment]
This seems to be fixed in the latest `HEAD` version. I can do `brew install fbsimctl --HEAD` without needing to do `export CODE_SIGNING_REQUIRED=NO`.
