### ISSUE TITLE
Run simulator with disabled Location or disable it after start of simulator

### ISSUE THREAD

**Issue by agileseph** [facebook/idb#362]
For some of the tests, I need to disable Location. I start simulator with FBSimCtl, so it forces the default location to latitude:37.485023 longitude:-122.147911.
How can I disable location via FBSimCtl or start simulator with already disabled location?

**Comment by lawrencelomax** [comment]
This is entirely configurable if you add options for this in `FBSimulatorBootConfiguration` and then react to these options in `FBSimulatorBootStrategy`
