### ISSUE TITLE
Missing Framework libswiftAppKit.dylib in Xcode 8.3

### ISSUE THREAD

**Issue by jmoody** [facebook/idb#375]
Updated ./build.sh to only run the device_control_framework tests.

### Xcode 8.2.1

```
$ DEVELOPER_DIR=/Xcode/8.2.1/Xcode.app/Contents/Developer ./build.sh devicectl test
Test Suite 'All tests' passed at 2017-02-10 11:44:38.724.
         Executed 11 tests, with 0 failures (0 unexpected) in 4.074 (4.081) seconds****
```

### Xcode 8.3 and 8.3.1

```
$ DEVELOPER_DIR=/Xcode/8.3/Xcode.app/Contents/Developer ./build.sh devicectl test
Failing tests:
        -[FBDeviceControlLinkerTests testLinksPrivateFrameworks]
        -[FBDeviceControlLinkerTests testReadsFromMobileDevice]

FBControlCore[48672] <Error>: Failed to load the Xcode frameworks for FBDeviceControl \
 with error Error Domain=com.facebook.FBControlCore Code=0 \
"Missing Framework libswiftAppKit.dylib
```

The framework that cannot be loaded is IDEFoundation.framework:

```
IDEFoundation: Bundle could not be loaded from 
/Xcode/8.3/Xcode.app/Contents/Frameworks/IDEFoundation.framework
```

**Comment by sapieneptus** [comment]
> /Xcode/8.3/Xcodebeta.app/Contents/Frameworks/IDEFoundation.framework

Does it just not exist?

**Comment by jmoody** [comment]
IDEFoundation.framework does exist.

I have demonstrated that if I load the required Swift dylibs with `dlopen` before trying to load the IDEFoundation.framework, I can get past this error and the failing tests pass. 

@lawrencelomax Would you be interested in such a solution?

**Comment by lawrencelomax** [comment]
The underlying reason for this is that `fbsimctl` and `IDEFoundation` both link different versions of the Swift Runtime Overlays. Swift is not currently ABI-Stable, so it can be extremely fraught to mix-and-match Frameworks that are build against different swift versions.

One 'workaround' is to make sure that the Swift Version that you build with is the same version as the Xcode you will run against. For example`IDEDocumentation` may-be linked with interacting with Devices. You can check for this are some internal Xcode Frameworks that use the Swift Runtime Overlays with the following command:

```
otool -l /Applications/xcode_8.2.app/Contents/Frameworks/IDEDocumentation.framework/IDEDocumentation |  grep -A 5 'libswiftCore.dylib'
```

There are two answers to how we can resolve these issues for good:
1) Swift 4 should be ABI Stable. Going forward this will mean that `fbsimctl` built Post-Swift-4 version and the Xcode Frameworks running against a different-post-swift-4 version will be able to coexist in the same process space.
2) Extract the need for these dependencies in the first place. The reason that we have so many dependencies on these Xcode `IDE` Frameworks is for device support. `MobileDevice.framework` is far more stable and are the primitives which these higher-level Frameworks are implemented. This has the added benefit that launch-times of `fbsimctl` when using will be drastically reduced as these large Frameworks won't need to be used at runtime.

I'll also take a look at @jmoody's workaround for a short-term fix.

**Comment by jmoody** [comment]
@lawrencelomax

I hesitate to ask because I cannot reproduce in FBSimulatorControl integration test, but have you seen anything like this before and/or is caused by linking 2 different versions of the swift dylibs?

```
[MT] DVTAssertions: ASSERTION FAILURE in /Library/Caches/com.apple.xbs/Sources/DVTFrameworks/DVTFrameworks-12125.1/DVTFoundation/DeveloperStructure/DVTExtendedPlatformInfo.m
:53
Details:  Multiple extensions found for platform 'com.apple.platform.macosx' for extension point 'Xcode.DVTFoundation.ExtendedPlatformInfo': {(
        (
        "<DVTExtension 0x7fb39887c1d0: Mac Extended Platform Info (Xcode.DVTFoundation.ExtendedPlatformInfo.Mac) v1.0 from com.apple.dt.DVTFoundation>",
        "/Xcode/8.3/Xcode-beta.app/Contents/SharedFrameworks/DVTFoundation.framework"
    ),
        (
        "<DVTExtension 0x7fb398947960: Mac Extended Platform Info (Xcode.DVTFoundation.ExtendedPlatformInfo.Mac) v1.0 from com.apple.dt.DVTFoundation>",
        "/Xcode/8.3/Xcode-beta.app/Contents/SharedFrameworks/DVTFoundation.framework"
    )
)}
Object:   <DVTExtendedPlatformInfo>
Method:   +extendedPlatformInfoForPlatformIdentifier:error:
Thread:   <NSThread: 0x7fb393e08eb0>{number = 1, name = main}
Hints:

Backtrace:
  0   -[DVTAssertionHandler handleFailureInMethod:object:fileName:lineNumber:assertionSignature:messageFormat:arguments:] (in DVTFoundation)
  1   _DVTAssertionHandler (in DVTFoundation)
  2   _DVTAssertionFailureHandler (in DVTFoundation)
  3   __75+[DVTExtendedPlatformInfo extendedPlatformInfoForPlatformIdentifier:error:]_block_invoke (in DVTFoundation)
  4   _dispatch_client_callout (in libdispatch.dylib)
  5   dispatch_once_f (in libdispatch.dylib)
  6   +[DVTExtendedPlatformInfo extendedPlatformInfoForPlatformIdentifier:error:] (in DVTFoundation)
  7   -[DVTPlatform(DVTExtendedPlatformInfo) dvt_extendedInfoOrError:] (in DVTFoundation)
  8   +[DVTPlatform validatePlatformDataReturningError:] (in DVTFoundation)
  9   IDEInitialize (in IDEFoundation)
 10   +[IDEFoundationTestInitializer initializeTestabilityWithUI:error:] (in IDEFoundation)
 11   +[FBDeviceControlFrameworkLoader initializePrincipalClasses:error:] at /Users/moody/git/calabash/FBSimulatorControl/FBDeviceControl/Utility/FBDeviceControlFrameworkLoader.m:139 (in FBDeviceControl)
 12   +[FBDeviceControlFrameworkLoader loadXcodeFrameworks:error:] at /Users/moody/git/calabash/FBSimulatorControl/FBDeviceControl/Utility/FBDeviceControlFrameworkLoader.m:87 (in FBDeviceControl)
 13   __59+[FBDeviceControlFrameworkLoader initializeXCodeFrameworks]_block_invoke at /Users/moody/git/calabash/FBSimulatorControl/FBDeviceControl/Utility/FBDeviceControlFrameworkLoader.m:75 (in FBDeviceControl)
```
