### ISSUE TITLE
Is it sensible to put 'shake simulator' into fbsimctl?

### ISSUE THREAD

**Issue by sleekweasel** [facebook/idb#378]
We want to test the shake gesture in our tests, without having to run at least one simulator with a head and direct shake-reliant tests to that device, then using applescript to send the 'shake' keyboard shortcut to the window.

I found some code about triggering shake here: http://stackoverflow.com/questions/10154958/ios-how-to-detect-shake-motion but while it looked like it ran in an iOS context, the WDA team said that wasn't something WDA could do and they closed the issue.

I had a look through the simulator control code, but I'm not familiar with MacOS/iOS development. Is shaking something that fbsimctl could tell the simulator to effect?

Thanks.

**Comment by lawrencelomax** [comment]
Yes this is absolutely possible. You can see how this is synthesized by the `Simulator.app` in the `-[SimDevice gsEventsSendShake]` method. This uses the `PurpleWorkspacePort` and `mach_msg_send` to synthesize a 'Purple' event to the Simulator.

You can read more about how the `Simulator.app` [synthesizes input events here](https://github.com/facebook/FBSimulatorControl/blob/master/Documentation/SimulatorHID.md). The headers for a `Purple` [event are available here](https://github.com/facebook/FBSimulatorControl/blob/master/PrivateHeaders/SimulatorApp/Purple.h)

**Comment by lawrencelomax** [comment]
Bear in mind that the code that you link to runs *inside* an Application by faking a shake notification. `FBSimulatorControl` does not have components that run *inside* a Simulator, it automates the Simulator from the outside. The approach that would make most sense for `FBSimulatorControl` is to use the APIs that the `Simulator.app` uses.

**Comment by sleekweasel** [comment]
I'm afraid I've resorted to running one simulator with a head and directing shake-aware tests to that one. We only have a few, so it's not the worst compromise.

**Comment by Jnaneshnayak** [comment]
@lawrencelomax little help here please -
looks like mach_msg_send is not triggered when a Shake event is initiated in the Simulator App.
I am tracing with `pid$target::mach_msg_send:entry` and can see mach messages for RotateLeft and RotateRight but none for Shake

This is puzzling because both `gsEventsSendOrientation` and `gsEventsSendShake` seem to be calling `sendPurpleEvent` which is turn should call `mach_msg_send`
