### ISSUE TITLE
How to launch ReactNative projects in fbsimctl-powered simulators? 

### ISSUE THREAD

**Issue by itinance** [facebook/idb#404]
Any ideas how to launch ReactNative-projects on all these iOS-simulators simultanously that was launched powered by fbsimctl?

When i launch the app with "`react-native run-ios`" it will only appear on the very first simulator that was launched. When i launch via XCode all other simulators will shutdown automatically except this one that was selected in the XCode launch-bar.

In the README is stated the command:

`fbsimctl launch com.facebook.someapp`

I replaced the app-id to mine and it did not help, but will output something like:

> Error Domain=com.facebook.FBSimulatorControl Code=0 "App com.myown.appid can't be launched as it isn't installed"

It is also mentioned to call

`fbsimctl install Someapp.app`

I tried it with an exported IPA directly out of XCode. It produces:

> Error Domain=com.facebook.FBSimulatorControl Code=0 "Could not determine Application information for path /private/var/folders/cj/c_zjt5x12ps_6q93t023qc4w0000gn/T/61863B0A-89D3-4002-ACC4-D31EC256BA50-70447-0000472A108998F9/Payload/XXXXXX.app" UserInfo={NSLocalizedDescription=Could not determine Application information for path /private/var/folders/cj/c_zjt5x12ps_6q93t023qc4w0000gn/T/61863B0A-89D3-4002-ACC4-D31EC256BA50-70447-0000472A108998F9/Payload/XXXXXX.app

Any ideas?

**Comment by lawrencelomax** [comment]
It looks like the IPA extraction component may be broken for this Application cc @zsol. 

If you manually `unzip` the `.ipa` can you install the `.app` using `fbsimctl install Someapp.app`? Does the path ending `Payload/XXXXXX.app` exist on your filesystem?

**Comment by zeyadsalloum** [comment]
We just released idb. a new tool that improves significantly over fbsimctl. idb can handle installation from a .ipa or a .app. We recommend switching over. As part of our renewed commitment to this repo we are cleaning up old issues and will be monitoring and reviewing more closely from now on. if you still think this issue is relevant feel free to reopen
