### ISSUE TITLE
Multiple Errors!!!

### ISSUE THREAD

**Issue by amusharraf** [facebook/idb#418]
Hi there, whenever i run a test any test on iPhones using the xcode simulators my log is muddied with errors of all sorts. Thus my tests also progress very slowly due to the errors and i do not know how to fix it. Here i have attached the logs that show the problems and all. I am using Appium: 1.6.6-beta. xcode = 8.3.3.

https://gist.github.com/amusharraf/a3318ad58599f6eac01aef7320984c39

**Comment by amusharraf** [comment]
Hello, I am running tests on Xcode simulators using appium but i am encountering multiple issues that can be seen in the logs that i have attached below. Please help me resolve these issues ASAP, some issues include:

Error: simctl error running fbsimctl:....
Failed to harvest strings for pathless uuid....
Failed to enable path: code=113...
Error in registering callback port
Could not create service from plist at path...
and a lot more

Environment

Appium version (or git revision) that exhibits the issue: 1.6.6-beta
Desktop OS/version used to run Appium: Sierra
Node.js version (unless using Appium.app|exe):
Mobile platform/version under test: iOS 10.2
Real device or emulator/simulator: Simulator

**Comment by zeyadsalloum** [comment]
We just released idb. a new tool that improves significantly over fbsimctl. We recommend switching over. As part of our renewed commitment to this repo we are cleaning up old issues and will be monitoring and reviewing more closely from now on. if you still think this issue is relevant feel free to reopen
