### ISSUE TITLE
Installation error: "build/Build/Products/Debug/!(*.framework): No such file or directory"

### ISSUE THREAD

**Issue by adamski** [facebook/idb#421]
I'm getting this error trying to install:

```
Copying Build output from build/Build/Products/Debug/!(*.framework) to /usr/local/Cellar/fbsimctl/HEAD-39b4dff/bin
cp: build/Build/Products/Debug/!(*.framework): No such file or directory
```

**Comment by chirag04** [comment]
same here

**Comment by adamski** [comment]
Updating to the latest version of node (8.1.3) from my previous installation (6.8.0) seems to have fixed this issue for me.

**Comment by adamski** [comment]
How to install manually so I can use `fbsimctl`?

**Comment by adamski** [comment]
I managed to get it installed manually by changing line 10 in `build.sh` from

```
BUILD_DIRECTORY=build
```
to

```
BUILD_DIRECTORY=fbsimctl
```

and manually building with 

```
./build.sh fbsimctl build /usr/local/Cellar/fbsimctl/HEAD-07b4203 
```
where the last part is the git commit hash of master (taken from the error message output in the first post)

then manually linking with 

```
brew link fbsimctl
```

YMMV - and I may have missed something as I tried a few different things...

**Comment by andyesp** [comment]
@adamski solution worked! 

This bug needs to be fixed :(

**Comment by zeyadsalloum** [comment]
We just released idb. a new tool that improves significantly over fbsimctl. We recommend switching over. As part of our renewed commitment to this repo we are cleaning up old issues and will be monitoring and reviewing more closely from now on. if you still think this issue is relevant feel free to reopen
