### ISSUE TITLE
FBAMDeviceStopSession causing exc_bad_access when compilier optimization are on

### ISSUE THREAD

**Issue by jmoody** [facebook/idb#425]
Our software uses the FBSimulatorControl frameworks.

I am in the process of updating our fork.  I notice that you are transitioning from the DVT APIs to the MobileServices API to solve Swift dylib loading problems on Xcode 8.3.  I would give steps to reproduce this problem, but the facebook/FBSimulatorControl master branch fails _before the problematic code_ because of these Swift dylib loading errors.

We have, on our fork, a workaround for loading the Swift dylibs: #377

If I compile the FBSimulatorControl frameworks with optimization "s" (smallest, fastest), I see the bad access.  If I compile with optimization "0" (none), the bad access does not occur.

This is where the problem occurs:

https://github.com/facebook/FBSimulatorControl/blob/master/FBDeviceControl/Management/FBAMDevice.m#L114

```
- (id)handleWithBlockDeviceSession:error:
...
  if (FBAMDeviceStartSession(_amDevice) == 0) {
    operationResult = operationBlock(_amDevice);
    FBAMDeviceStopSession(_amDevice);  ==> exc_bad_access code=exc_i386_gpflt
  } else {
    [[FBDeviceControlError
      describe:@"Failed to start session with device."]
     fail:error];
  }
```

This is the stack trace:

```
0 AMDeviceStopSession
1 FBAMDevice handleWithBlockDeviceSession:error
2 FBiOSDeviceOperator handleWithAFCSession:error:
3 FBiOSDeviceOperator transferAppURL:options:error:
4 FBiOSDeviceOperator installApplicationWithPath:error:
```

I have tried to sort out where the problem is occurring.  I ran the static analyzer on FBDeviceControl and found a couple problems that could have been related, but they did not change the behavior.

**Comment by zeyadsalloum** [comment]
should be fixed now
