### ISSUE TITLE
Error: While installing 'fbsimctl' dependencies

### ISSUE THREAD

**Issue by kantharia** [facebook/idb#429]
I am following getting started [documentation](https://github.com/wix/detox/blob/master/docs/Introduction.GettingStarted.md). I got stuck on Step 1 -> 3. Install fbsimctl.

I am getting errors : 
- error: 'FBSimulatorControl/FBSimulatorControl.h' file not found

**_Please check screenshot for details_**

![screen shot 2017-07-11 at 4 18 03 pm](https://user-images.githubusercontent.com/8065874/28065068-a5b65df2-6654-11e7-9b86-82dc6b22fe8f.png)

**Comment by LeoNatan** [comment]
The current requirement of installing from HEAD, while the project is unstable in the master branch is a particularly bad combination. There should be stable releases so that specific versions can be pinned for installing.

**Comment by kantharia** [comment]
@LeoNatan - Is there any workaround, like installing from specific tag or commit hash

**Comment by hendricius** [comment]
Having the same issue. How can I install a specific version?

**Comment by hendricius** [comment]
Quick update, I followed the instructions for installing a custom version. I picked a commit hash where it still worked. Then I updated my circle.yml file:

```
  - git clone https://github.com/facebook/FBSimulatorControl.git
  - cd FBSimulatorControl && git checkout 2a461c4e31f12b29974a5a6d184126c2526c62d1 && ./build.sh fbsimctl build output && cd ../
  - mv FBSimulatorControl/output/Frameworks/* /usr/local/Frameworks/
  - mv FBSimulatorControl/output/bin/* /usr/local/bin/
```

**Comment by hendricius** [comment]
It would be great to have one semi stable version available. Then the `--HEAD` part can be omitted.

**Comment by zeyadsalloum** [comment]
We just released idb. a new tool that improves significantly over fbsimctl. We recommend switching over. As part of our renewed commitment to this repo we are cleaning up old issues and will be monitoring and reviewing more closely from now on. if you still think this issue is relevant feel free to reopen
