### ISSUE TITLE
fbsimctl stream

### ISSUE THREAD

**Issue by DanielPradoPino** [facebook/idb#434]
Hi guys,

First thanks for this amazing tool, I am trying to stream simulator screen to http, I know I can execute fbsimctl stream but how I should get the stream?

Sorry for my ignorance...

**Comment by SloNN** [comment]
Hi,

fbsimctl <DeviceID> stream --h264  -|ffmpeg -f h264 -i pipe:0 -vcodec copy -tune zerolatency -b 900k -f mpegts udp://127.0.0.1:12345

I've streamed over udp, so you need to find correct command line for ffmpeg to stream over http in your format

**Comment by DanielPradoPino** [comment]
Hi SloNN, 

Thanks for answering, this is not working for me, if I put this "-" at the end of fbsimctl command is giving error and if I don't put it it just stops in fbsimctl execution and not continue with ffmpeg. 
Sorry for being so neebie with this, can you please help me with this?

**Comment by SloNN** [comment]
Sorry, I've completely removed DeviceID from the example, should be

fbsimctl <YourDeviceID> stream --h264 -|ffmpeg -f h264 -i pipe:0 -vcodec copy -tune zerolatency -b 900k -f mpegts udp://127.0.0.1:12345

**Comment by DanielPradoPino** [comment]
Hi SloNN,

Thanks a gain for reply, this is not working for me anyway, it is throwing just a fbsimctl syntax error... I don't really know what I am doing wrong in here.

Thanks again.

**Comment by JonGabilondoAngulo** [comment]
Hi,
I'm trying it without success, 

fbsimctl YourDeviceID stream --bgra -|ffmpeg -f h264 -i pipe:0 -vcodec copy -tune zerolatency -b 900k -f mpegts udp://127.0.0.1:12345

Above is mentioned that the format is h264. In my tries, fsimctrl says it can only do bgra on simulators.
fbsimctl seems to advance but I get no connection to the UDP address using VLC viewer.
Anyone with more luck ?
Thanks

**Comment by ahmadaliraza** [comment]
@JonGabilondoAngulo  bgra stream coming from fbsimctl is raw bgr frames input for ffmpeg not h264 stream

try to use `-f rawvideo` instead of `-f h264`

`fbsimctl YourDeviceID stream --bgra -|ffmpeg -f rawvideo -pixel_format bgra -s:v 508x904 -framerate 30 -i pipe:0 -vcodec mpeg -tune zerolatency -b 900k -f mpegts udp://127.0.0.1:12345`

framerate and video size options can be changed accordingly. also you can set --fps in fbsimctl stream command as well

**Comment by JonGabilondoAngulo** [comment]
No luck still,

Does your example work ? What viewer do you use ?

If this would work on a physical device using VLC viewer:
fbsimctl stream --h264 -| ffmpeg -f h264 -i pipe:0 -vcodec copy   -f rtp_mpegts udp://127.0.0.1:12345

The correspondant on Simulator doesn't:
fbsimctl stream --bgra -| ffmpeg -f rawvideo -pixel_format bgra -s:v 432x769 -framerate 12  -i pipe:0 -vcodec copy   -f rtp_mpegts udp://127.0.0.1:12345

Nor for HLS:
fbsimctl stream --bgra -| ffmpeg -f rawvideo -pixel_format bgra -s:v 432x769 -framerate 12 -i pipe:0 -vcodec copy  -f hls -hls_time 1 -hls_list_size 1 -hls_flags delete_segments  -hls_segment_filename /Library/WebServer/Documents/vid_%03d.ts  /Library/WebServer/Documents/vid.m3u8

Thanks

**Comment by ahmadaliraza** [comment]
@JonGabilondoAngulo  try removing `-vcodec copy` for raw video and hls output and set `--framerate 12` in fbsimctl stream matching the framerate value of ffmpeg

**Comment by ahmadaliraza** [comment]
@JonGabilondoAngulo  there is missing device udid in command. to verify fbsimctl stream, try a plain playback of fbsimctl stream with

` fbsimct <UDID> stream --bgra --fps 12 - | ffplay -f rawvideo -pixel_format bgra -s 432x769 -i - `

change UDID and device resolution parameters accordingly

if you see proper device stream or blurry view, means your fbsimctl stream is working, it might be issue with ffmpeg processing

**Comment by stoefln** [comment]
How do I run this with idb command line tool?
