### ISSUE TITLE
Unable to run iOS test cases in parallel on two iOS simulators

### ISSUE THREAD

**Issue by pgajeshwar-coupa** [facebook/idb#445]
Hi,

I am trying to run parallel test cases on iOS simulator but unable to achieve parallel execution. Issue is when I am running test cases on first simulator and then start running test cases on second simulator then application running on first simulator terminates with error message (UNSUserNotificationServerConnectionListener connection invalidated).
Full log:
```
Sep 15 17:42:00 Pareshs-MacBook-Pro CoreSimulatorBridge[16254]: Pasteboard change listener callback port <NSMachPort: 0x7ff27d301980> registered
Sep 15 17:42:25 Pareshs-MacBook-Pro SpringBoard[16248]: UNSUserNotificationServerConnectionListener connection invalidated
Sep 15 17:42:25 Pareshs-MacBook-Pro SpringBoard[16248]: [KeyboardArbiter] HW kbd: Failed to set (null) as keyboard focus
Sep 15 17:42:25 Pareshs-MacBook-Pro com.apple.CoreSimulator.SimDevice.8369BE0F-F1B1-4D05-B13E-9A7C26E7F277.launchd_sim[16231] (UIKitApplication:com.push.paresh[0x5e7e][16253][16656]): Service exited due to Killed: 9
Sep 15 17:42:25 Pareshs-MacBook-Pro backboardd[16249]: [Common] Unable to get short BSD proc info for 16656: No such process
Sep 15 17:42:25 Pareshs-MacBook-Pro backboardd[16249]: [Common] Unable to get proc info for 16656: Undefined error: 0
Sep 15 17:42:25 Pareshs-MacBook-Pro assertiond[16253]: Deleted job with label: UIKitApplication:com.push.paresh[0x5e7e][16253]

```

**Comment by zeyadsalloum** [comment]
We just released idb. a new tool that improves significantly over fbsimctl. idb supports running simulators in parallel. We recommend switching over. As part of our renewed commitment to this repo we are cleaning up old issues and will be monitoring and reviewing more closely from now on. if you still think this issue is relevant feel free to reopen
