### ISSUE TITLE
Simulator Archs ([x86_64, i386])" UserInfo={NSLocalizedDescription=Simulator does not support any of the architectures ([arm, arm64]) of the executable at [path]. What does this mean?

### ISSUE THREAD

**Issue by WFNeIn** [facebook/idb#447]

**Comment by plu** [comment]
Your app was built for a real device (`arm`, `arm64`), but the Simulator on Mac OS needs your app being compiled for either `x86_64` or `i386`, depending on which Simulator device type you're using.
