### ISSUE TITLE
Is the management layer above fbsimctl open source?

### ISSUE THREAD

**Issue by sleekweasel** [facebook/idb#449]
We're about to try to shift from a system where we set up 30 simulators on parallel macs over ssh, while the app takes 8 minutes to build, to having a simulator server that provides simulators on request.

Is that an open source project? Could you mention it from the fbsimctl page if it is?

Thanks

**Comment by zsol** [comment]
It's not open source unfortunately :(

**Comment by NickAb** [comment]
Do you have any articles that provide any information on management layer or its architecture?

**Comment by sleekweasel** [comment]
Good to know - saves me reading through all your projects! :)

We'll seek to publish ours once it's written, and we'll try not to tie it too closely to Parallel Cucumber.

**Comment by lawrencelomax** [comment]
There's an [article here](https://code.fb.com/android/managing-resources-for-large-scale-testing/). As well as a [talk here](https://www.youtube.com/watch?v=2s0nfn9I524) and a [more recent one](https://atscaleconference.com/videos/scale-2018-one-world-scalable-resource-management/).

The TLDR; is that we call this "One World" and it's used for match-making across different runtimes and providing them to tests. We don't have any plans for OSSing "One World" itself, but you should be able to get an idea of the important aspects of it's design from these talks. If you have specific questions we may also be able to answer them if you have questions about them. We'd be happy to address these in GitHub issues.

`idb` was not previously public and was really the "missing piece" for how we allow for remote iOS Automation. It [is now](https://developers.facebook.com/videos/2019/reliable-code-at-scale/) and you can see from the F8 talk that we reference `idb` as being the "interface for automation". This means that "One World" gives out `idb` companions as this interface.
