### ISSUE TITLE
Cocoapods support

### ISSUE THREAD

**Issue by VincentCATILLON** [facebook/idb#460]
Hi guys,

Thanks for your work !
We added your framework into our project, but we were surprised that we can't use it as a Cocoapods dependency.

Could you add a Podfile to your project to avoid this ?
<img width="143" alt="capture d ecran 2017-10-17 a 09 54 28" src="https://user-images.githubusercontent.com/8419208/31653130-bd02b932-b321-11e7-9d59-668bcfd28178.png">

Have a good day 👍

**Comment by zeyadsalloum** [comment]
We just released idb. a new tool that improves significantly over fbsimctl. We recommend switching over. As part of our renewed commitment to this repo we are cleaning up old issues and will be monitoring and reviewing more closely from now on.
