### ISSUE TITLE
cannot launch_xctest

### ISSUE THREAD

**Issue by colinator** [facebook/idb#462]
I'm doing this:

./fbsimctl 638490F0-98EE-4713-B3A9-B3E1F6321908 launch_xctest /Users/.../DerivedData/APPNAME-cljfdjcevrmklzccqjfftprbwzop/Build/Products/Debug-iphonesimulator/APPNAME.app/PlugIns/OURTESTS.xctest com.something.whatever -- listen

and I see this:

```
Overriding the Default Logger with <LogReporter: 0x7fa692e012f0>

Application Did Launch => Process APPNAME | PID 46123
638490F0-98EE-4713-B3A9-B3E1F6321908 | iPhone 8 | Booted | iPhone 8 | iOS 11.0 | x86_64: launch: Process APPNAME | PID 46261
Connecting Test Bundle
Creating the test bundle connection.
Listening for proxy connection request from the test bundle (all platforms)
Resuming the test bundle connection.
Checking test manager availability...
Starting test session with ID 2E6EFB56-CA65-45AD-8941-697CDD9B1FE0
testmanagerd handled session request using protcol version 22.
Application Did Terminate => Expected 0 Process APPNAME | PID 46804
638490F0-98EE-4713-B3A9-B3E1F6321908 | iPhone 8 | Booted | iPhone 8 | iOS 11.0 | x86_64: terminate: Process APPNAME | PID 46804
```

I see the app launch, and then immediately terminate.

and then a few seconds later:

`Error Domain=com.facebook.FBSimulatorControl Code=0 "Failed start test manager" UserInfo={NSLocalizedDescription=Failed start test manager, NSUnderlyingError=0x7f8c3c781fe0 {Error Domain=com.facebook.FBControlCore Code=0 "Timed out waiting for future Future running in 30.000000 seconds" UserInfo={NSLocalizedDescription=Timed out waiting for future Future running in 30.000000 seconds}}}`

**Comment by zeyadsalloum** [comment]
We just released idb. a new tool that improves significantly over fbsimctl. We recommend switching over. As part of our renewed commitment to this repo we are cleaning up old issues and will be monitoring and reviewing more closely from now on. if you still think this issue is relevant feel free to reopen
