### ISSUE TITLE
iOS 11 - Test execution fails after 2-3 hours of execution on real iOS devices

### ISSUE THREAD

**Issue by raamojirao** [facebook/idb#464]
Test execution stops after 2-3 hours on iOS 11 devices. The same setup works fine for iOS 10 devices where tests run for 24+ hours. gems being used - run_loop - 2.6.1/2.6.0/2.5.4 calabash-cucumber - 0.21.1/0.20.5 cucumber - 3.0.0.pre.2 Xcode - 9 iOS - 11.0/11.0.1/11.0.2

Below is the error message -

> Could not install /Users/raenug001c/.rvm/gems/ruby-2.3.1@ios11test/gems/run_loop-2.6.1/lib/run_loop/device_agent/ipa/DeviceAgent-Runner.app. iOSDeviceManager says:
 Error getting device with ID 630826b68345ba162bc2494709ff39657dd3c122: Error Domain=com.facebook.FBControlCore Code=0 “Failed to load device console entries” UserInfo={NSLocalizedDescription=Failed to load device console entries}
> install <app-path>
            -d,--device-id  <device-identifier>     iOS Simulator GUID or 40-digit physical device ID
            -u,--update-app <should-update-app> [OPTIONAL]  When true, will reinstall the app if the device contains an older version than the bundle specified     DEFAULT=1
            -p,--profile-path       <profile-path> [OPTIONAL]       Path to provisioning profile
            -c,--codesign-identity  <codesign-identifier> [OPTIONAL]        Identity used to codesign app bundle [device only]. Deprecated - should use profile path.       DEFAULT=
            -i,--resources-path     <resources-path> [OPTIONAL]     Path to resources (executables) to inject into app directory. A list of colon separated files may be specified.
> (RuntimeError)
  /Users/raenug001c/Documents/testios11/tvx-mobile-automation/iOS/common/support/01_launch.rb:49:in `Before’

Only after the restarting the device, the tests can be executed further.

After further debugging the issue, seems like iOSDeviceManager is unable to install/launch device agent app on the device. Unable to view the source code for iOSDeviceManager, hence not able to debug further. Could someone help in this.

**Comment by otamas94** [comment]
For me it's happening on an iOS device with iOS 9.3.2 and 10.3.2 too. XCode 8.3.3, run_loop 2.4.1 and calabash-cucumber 0.20.5. I don't know why, it came up couple of days ago, and after 2 hours of execution it fails always with the same error message.

**Comment by DoubleJ2011** [comment]
Also meet the same issue but more critical.

Upgrade iOS device to 11.1
Xcode 9.1
Upgrade calabash-ios version to 0.21.2
$ calabash-ios version
0.21.2
run_loop version is 2.6.1

Then uninstall test app and my target app. Then try to run test failed.

After debug it meet the same error message.

> calabash-ios 0.21.2> start_test_server_in_background
> RuntimeError: 
> 
> Could not install /Users/moxtra/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/run_loop-2.6.1/lib/run_loop/device_agent/ipa/DeviceAgent-Runner.app.  iOSDeviceManager says:
> 
> Error getting device with ID f1e7917dd0d60ede8da10a442d2e2bb16d4c741f: Error Domain=com.facebook.FBControlCore Code=0 "Failed to load device console entries" UserInfo={NSLocalizedDescription=Failed to load device console entries}
> 
> 	install <app-path>
> 		-d,--device-id	<device-identifier>	iOS Simulator GUID or 40-digit physical device ID
> 		-u,--update-app	<should-update-app> [OPTIONAL] 	When true, will reinstall the app if the device contains an older version than the bundle specified	DEFAULT=1
> 		-p,--profile-path	<profile-path> [OPTIONAL] 	Path to provisioning profile
> 		-c,--codesign-identity	<codesign-identifier> [OPTIONAL] 	Identity used to codesign app bundle [device only]. Deprecated - should use profile path.	DEFAULT=
> 		-i,--resources-path	<resources-path> [OPTIONAL] 	Path to resources (executables) to inject into app directory. A list of colon separated files may be specified.
> 
> 
> 	from /Users/moxtra/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/run_loop-2.6.1/lib/run_loop/device_agent/ios_device_manager.rb:149:in `launch'
> 	from /Users/moxtra/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/run_loop-2.6.1/lib/run_loop/device_agent/client.rb:1378:in `launch_cbx_runner'
> 	from /Users/moxtra/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/run_loop-2.6.1/lib/run_loop/device_agent/client.rb:292:in `launch'
> 	from /Users/moxtra/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/run_loop-2.6.1/lib/run_loop/device_agent/client.rb:167:in `run'
> 	from /Users/moxtra/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/run_loop-2.6.1/lib/run_loop.rb:113:in `run'
> 	from /Users/moxtra/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/calabash-cucumber-0.21.2/lib/calabash-cucumber/launcher.rb:414:in `block in new_run_loop'
> 	from /Users/moxtra/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/calabash-cucumber-0.21.2/lib/calabash-cucumber/launcher.rb:412:in `times'
> 	from /Users/moxtra/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/calabash-cucumber-0.21.2/lib/calabash-cucumber/launcher.rb:412:in `new_run_loop'
> 	from /Users/moxtra/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/calabash-cucumber-0.21.2/lib/calabash-cucumber/launcher.rb:365:in `relaunch'
> 	from /Users/moxtra/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/calabash-cucumber-0.21.2/lib/calabash-cucumber/core.rb:1567:in `start_test_server_in_background'
> 	from (irb):2
> 	from /Users/moxtra/.rbenv/versions/2.3.1/bin/irb:11:in `<main>'

**Comment by sankalpanand** [comment]
Same problem-

```
testmaskin$ /Users/testmaskin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/run_loop-2.6.1/lib/run_loop/device_agent/bin/iOSDeviceManager install /Users/testmaskin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/run_loop-2.6.1/lib/run_loop/device_agent/ipa/DeviceAgent-Runner.app --device-id b37cefb88fdc79200784844aa4f74ed95a0858db
2017-11-08 18:20:08.052 iOSDeviceManager[1070:35875] [MT] DVTPlugInManager: Required plug-in compatibility UUID C3998872-68CC-42C2-847C-B44D96AB2691 for MobileDevice.framework (com.apple.mobiledevice) not present
Error getting device with ID b37cefb88fdc79200784844aa4f74ed95a0858db: Error Domain=com.facebook.FBControlCore Code=0 "Failed to load device console entries" UserInfo={NSLocalizedDescription=Failed to load device console entries}
```

**Comment by lawrencelomax** [comment]
I think there's an internal timeout in `testmanagerd` that will drop all connections after a given time period. There's no reasonable way for us to change this for devices. 

Is it possible to change your test sequences to be shorter?
