### ISSUE TITLE
Potential resource leak: FBSimulatorBridge may open multiple SimulatorBridge services

### ISSUE THREAD

**Issue by wei-gu** [facebook/idb#466]
os: macOS 10.12.6
fbsimctl: latest build from src
simulator: iPhone 7, ios11
command: fbsimctl [sim udid] set_location [lat, long]

keep typing the command

**Comment by wei-gu** [comment]
![leak](https://user-images.githubusercontent.com/31942746/31961524-cf2d444a-b8af-11e7-9b45-cb209fceeb12.png)
update screenshot

**Comment by MoOx** [comment]
I am getting issue on my CI server which run functional testing via detox (which use fbsimctl).
Looks like a bug somehow. Any idea if that's related to FBSimulatorControl?
Can this be a lower level issue?

**Comment by zeyadsalloum** [comment]
We just released idb. a new tool that improves significantly over fbsimctl. We recommend switching over. As part of our renewed commitment to this repo we are cleaning up old issues and will be monitoring and reviewing more closely from now on. if you still think this issue is relevant feel free to reopen

**Comment by lawrencelomax** [comment]
I think I fixed this a while back. @MoOx do you mind confirming that this is fixed?

**Comment by MoOx** [comment]
@lawrencelomax sorry I don't use this tool in my current project so I cannot verify atm.

**Comment by lawrencelomax** [comment]
I've validate there are no leaks with 

```
$ repeat 100 idb ui describe-all
```

This will run a bridge command in a loop. There were some issues with Xcode 10 and bridges and I fixed these at the time so I'm guessing this was fixed at this point.
