### ISSUE TITLE
failed to start sim11.1 with hid 

### ISSUE THREAD

**Issue by gu-wei** [facebook/idb#467]
bit: built from master
output:
Wei-Dev-Mac:Debug weigu$ ./fbsimctl F6E0699A-BC9E-4905-B8B6-6BB67A55735F boot --direct-launch -- listen --http 8888 --socket 5000

Simulator Did launch => Process launchd_sim | PID 15260
F6E0699A-BC9E-4905-B8B6-6BB67A55735F | iPhone 8 | Booting | iPhone 8 | iOS 11.1 | x86_64: launch: Process launchd_sim | PID 15260
Did Change State => Booting
F6E0699A-BC9E-4905-B8B6-6BB67A55735F | iPhone 8 | Booting | iPhone 8 | iOS 11.1 | x86_64: state: Booting
Did Change State => Booted
F6E0699A-BC9E-4905-B8B6-6BB67A55735F | iPhone 8 | Booted | iPhone 8 | iOS 11.1 | x86_64: state: Booted
Connection Did Connect => Bridge: Framebuffer ((null)) | HID Indigo HID Port: Registered 15119 but no reply port | (null)
F6E0699A-BC9E-4905-B8B6-6BB67A55735F | iPhone 8 | Booted | iPhone 8 | iOS 11.1 | x86_64: launch: Bridge: Framebuffer ((null)) | HID Indigo HID Port: Registered 15119 but no reply port | (null)

2017-11-02 14:20:49.149 fbsimctl[15258:125040] +[FBLogTailConfiguration actionType]: unrecognized selector sent to class 0x10c2ad988
2017-11-02 14:20:49.150 fbsimctl[15258:125040] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '+[FBLogTailConfiguration actionType]: unrecognized selector sent to class 0x10c2ad988'
*** First throw call stack:
(
	0   CoreFoundation                      0x00007fff9d7222cb __exceptionPreprocess + 171
	1   libobjc.A.dylib                     0x00007fffb253848d objc_exception_throw + 48
	2   CoreFoundation                      0x00007fff9d7a3e44 +[NSObject(NSObject) doesNotRecognizeSelector:] + 132
	3   CoreFoundation                      0x00007fff9d694755 ___forwarding___ + 1061
	4   CoreFoundation                      0x00007fff9d6942a8 _CF_forwarding_prep_0 + 120
	5   FBControlCore                       0x000000010c232a2c +[FBiOSActionRouter actionMappingForActionClasses:] + 380
	6   FBControlCore                       0x000000010c232837 +[FBiOSActionRouter routerForTarget:actionClasses:] + 103
	7   FBControlCore                       0x000000010c232781 +[FBiOSActionRouter routerForTarget:] + 305
	8   FBControlCore                       0x000000010c25d7ca +[FBiOSActionReader socketReaderForTarget:delegate:port:] + 122
	9   FBSimulatorControlKit               0x000000010beca352 _T021FBSimulatorControlKit12ListenRunnerV13makeBaseRelayAA0D9InterfaceV_AA0H0_pSo23FBEventReporterProtocol_pSo22FBTerminationAwaitable_pSgtyKF + 5810
	10  FBSimulatorControlKit               0x000000010bec3a61 _T021FBSimulatorControlKit12ListenRunnerV3runAA13CommandResultVyF + 833
	11  FBSimulatorControlKit               0x000000010bec101b _T021FBSimulatorControlKit12ActionRunnerV3runAA13CommandResultVyF + 9579
	12  FBSimulatorControlKit               0x000000010bebb6c6 _T021FBSimulatorControlKit13CommandRunnerV3runAA0D6ResultVyF + 5222
	13  FBSimulatorControlKit               0x000000010beb9a82 _T021FBSimulatorControlKit17BaseCommandRunnerV3runAA0E6ResultVyF + 3378
	14  FBSimulatorControlKit               0x000000010bdf35dc _T021FBSimulatorControlKit9CLIRunnerV3runAA13CommandResultVyF + 2188
	15  FBSimulatorControlKit               0x000000010bdf21a1 _T021FBSimulatorControlKit9CLIRunnerV12runForStatuss5Int32VyF + 33
	16  FBSimulatorControlKit               0x000000010bdef523 _T021FBSimulatorControlKit15CLIBootstrapperC9bootstraps5Int32VyFZ + 2611
	17  FBSimulatorControlKit               0x000000010bdf26f8 _T021FBSimulatorControlKit15CLIBootstrapperC9bootstraps5Int32VyFZTo + 24
	18  fbsimctl                            0x000000010bde0568 main + 56
	19  libdyld.dylib                       0x00007fffb2e1e235 start + 1
	20  ???                                 0x000000000000000a 0x0 + 10
)
libc++abi.dylib: terminating with uncaught exception of type NSException
Abort trap: 6

**Comment by shauvik** [comment]
I'm seeing a similar error for the accessibility_fetch command.

```
./output/bin/fbsimctl 464B318D-E440-4536-9348-79B9A61E4047 accessibility_fetch

Connection Did Connect => Bridge: Framebuffer ((null)) | HID (null) | (null)
464B318D-E440-4536-9348-79B9A61E4047 | iPhone X | Booted | iPhone X | iOS 11.1 | x86_64: launch: Bridge: Framebuffer ((null)) | HID (null) | (null)
Agent Did Launch => <FBSimulatorAgentOperation: 0x7f8fac533310>
464B318D-E440-4536-9348-79B9A61E4047 | iPhone X | Booted | iPhone X | iOS 11.1 | x86_64: launch: Process SimulatorBridge | PID 4606
2017-11-11 18:33:58.502 fbsimctl[4604:317741] -[FBReportingiOSActionReaderDelegate obtainConsumerForAction:target:]: unrecognized selector sent to instance 0x7f8fadc06f80
2017-11-11 18:33:58.507 fbsimctl[4604:317741] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[FBReportingiOSActionReaderDelegate obtainConsumerForAction:target:]: unrecognized selector sent to instance 0x7f8fadc06f80'
*** First throw call stack:
(
	0   CoreFoundation                      0x00007fff8fd9c2cb __exceptionPreprocess + 171
	1   libobjc.A.dylib                     0x00007fffa4bb448d objc_exception_throw + 48
	2   CoreFoundation                      0x00007fff8fe1df04 -[NSObject(NSObject) doesNotRecognizeSelector:] + 132
	3   CoreFoundation                      0x00007fff8fd0e54a ___forwarding___ + 538
	4   CoreFoundation                      0x00007fff8fd0e2a8 _CF_forwarding_prep_0 + 120
	5   FBSimulatorControl                  0x000000010d3e331d -[FBAccessibilityFetch runWithTarget:delegate:error:] + 365
	6   FBSimulatorControlKit               0x000000010d158ea5 _T0So17FBiOSTargetActionP21FBSimulatorControlKitE03runC0So19FBTerminationHandle_pSgSo0aB0_p6target_So23FBEventReporterProtocol_p8reportertKF + 517
	7   FBSimulatorControlKit               0x000000010d13547a _T021FBSimulatorControlKit15iOSTargetRunnerV4coreAcA11iOSReporter_p_SC11FBEventNameVSgSo03FBiD0_pSo0jD6Action_ptFZSo19FBTerminationHandle_pSgyKcfU_ + 154
	8   FBSimulatorControlKit               0x000000010d13560e _T021FBSimulatorControlKit15iOSTargetRunnerV4coreAcA11iOSReporter_p_SC11FBEventNameVSgSo03FBiD0_pSo0jD6Action_ptFZSo19FBTerminationHandle_pSgyKcfU_TA + 126
	9   FBSimulatorControlKit               0x000000010d135960 _T021FBSimulatorControlKit15iOSTargetRunnerV3runAA13CommandResultVyF + 512
	10  FBSimulatorControlKit               0x000000010d1361b9 _T021FBSimulatorControlKit15iOSTargetRunnerVAA0E0A2aDP3runAA13CommandResultVyFTW + 185
	11  FBSimulatorControlKit               0x000000010d11d980 _T021FBSimulatorControlKit21SimulatorActionRunnerV3runAA13CommandResultVyF + 2848
	12  FBSimulatorControlKit               0x000000010d122061 _T021FBSimulatorControlKit21SimulatorActionRunnerVAA0F0A2aDP3runAA13CommandResultVyFTW + 689
	13  FBSimulatorControlKit               0x000000010d167a77 _T021FBSimulatorControlKit14SequenceRunnerV3runAA13CommandResultVyF + 583
	14  FBSimulatorControlKit               0x000000010d1c64b6 _T021FBSimulatorControlKit12ActionRunnerV3runAA13CommandResultVyF + 15446
	15  FBSimulatorControlKit               0x000000010d1bf476 _T021FBSimulatorControlKit13CommandRunnerV3runAA0D6ResultVyF + 5222
	16  FBSimulatorControlKit               0x000000010d1bd832 _T021FBSimulatorControlKit17BaseCommandRunnerV3runAA0E6ResultVyF + 3378
	17  FBSimulatorControlKit               0x000000010d0f61cc _T021FBSimulatorControlKit9CLIRunnerV3runAA13CommandResultVyF + 2188
	18  FBSimulatorControlKit               0x000000010d0f4d91 _T021FBSimulatorControlKit9CLIRunnerV12runForStatuss5Int32VyF + 33
	19  FBSimulatorControlKit               0x000000010d0f2113 _T021FBSimulatorControlKit15CLIBootstrapperC9bootstraps5Int32VyFZ + 2611
	20  FBSimulatorControlKit               0x000000010d0f52e8 _T021FBSimulatorControlKit15CLIBootstrapperC9bootstraps5Int32VyFZTo + 24
	21  fbsimctl                            0x000000010d0dc578 main + 56
	22  libdyld.dylib                       0x00007fffa549a235 start + 1
	23  ???                                 0x0000000000000003 0x0 + 3
)
libc++abi.dylib: terminating with uncaught exception of type NSException
[1]    4604 abort      ./output/bin/fbsimctl 464B318D-E440-4536-9348-79B9A61E4047 accessibility_fetc
```

**Comment by shauvik** [comment]
Even the first action (boot) doesn't work for me.
```
./output/bin/fbsimctl 464B318D-E440-4536-9348-79B9A61E4047 boot                

No Simulator Application found for device set '/Users/shauvik/Library/Developer/CoreSimulator/Devices', launching a Simulator App for 464B318D-E440-4536-9348-79B9A61E4047 | iPhone X | Booting | iPhone X | iOS 11.1 | x86_64 | 0 | 0
Error Domain=com.facebook.FBSimulatorControl Code=0 "Could not obtain process info for container application" UserInfo={NSLocalizedDescription=Could not obtain process info for container application}
```

**Comment by zeyadsalloum** [comment]
We just released idb. a new tool that improves significantly over fbsimctl. We recommend switching over. As part of our renewed commitment to this repo we are cleaning up old issues and will be monitoring and reviewing more closely from now on. if you still think this issue is relevant feel free to reopen
