### ISSUE TITLE
Support for Xcode 9.3 launching real devices?

### ISSUE THREAD

**Issue by shepting** [facebook/idb#479]
## Steps
- `git pull`
- `./build.sh fbsimctl build ~/workspace/apps/ios/`
- plug in iPhone X running 11.3.1
- `cd ~/workspace/apps/ios`
- `./bin/fbsimctl launch com.airbnb.app`

## Error Message
`Library not loaded: @rpath/DebugHierarchyFoundation.framework/Versions/A/DebugHierarchyFoundation Reason: image not found`

**Full log:**

```steven_hepting@macbook:~/workspace/apps/ios(master) $ ./bin/fbsimctl launch com.airbnb.app
2018-04-26 17:40:46.916 fbsimctl[81672:1454506] [MT] DVTPlugInLoading: Failed to load code for plug-in com.apple.dt.dbg.DebuggerFoundation (/Applications/Xcode.app/Contents/PlugIns/DebuggerFoundation.ideplugin), error = Error Domain=NSCocoaErrorDomain Code=3587 "dlopen_preflight(/Applications/Xcode.app/Contents/PlugIns/DebuggerFoundation.ideplugin/Contents/MacOS/DebuggerFoundation): Library not loaded: @rpath/DebugHierarchyFoundation.framework/Versions/A/DebugHierarchyFoundation
  Referenced from: /Applications/Xcode.app/Contents/PlugIns/DebuggerFoundation.ideplugin/Contents/MacOS/DebuggerFoundation
  Reason: image not found" UserInfo={NSLocalizedFailureReason=The bundle is damaged or missing necessary resources., NSLocalizedRecoverySuggestion=Try reinstalling the bundle., NSFilePath=/Applications/Xcode.app/Contents/PlugIns/DebuggerFoundation.ideplugin/Contents/MacOS/DebuggerFoundation, NSDebugDescription=dlopen_preflight(/Applications/Xcode.app/Contents/PlugIns/DebuggerFoundation.ideplugin/Contents/MacOS/DebuggerFoundation): Library not loaded: @rpath/DebugHierarchyFoundation.framework/Versions/A/DebugHierarchyFoundation
  Referenced from: /Applications/Xcode.app/Contents/PlugIns/DebuggerFoundation.ideplugin/Contents/MacOS/DebuggerFoundation
  Reason: image not found, NSBundlePath=/Applications/Xcode.app/Contents/PlugIns/DebuggerFoundation.ideplugin, NSLocalizedDescription=The bundle “DebuggerFoundation” couldn’t be loaded because it is damaged or missing necessary resources.}, dyldError = 
2018-04-26 17:40:46.916 fbsimctl[81672:1454506] [MT] DVTAssertions: Warning in /Library/Caches/com.apple.xbs/Sources/IDEFrameworks/IDEFrameworks-14154/IDEFoundation/Initialization/IDEInitialization.m:265
```

## Questions
Is this flow supported? Does `fbsimctl` work with Xcode 9.x to run on real devices? I've gone back to Xcode 8.3 as well and still run into the same error.

**Comment by sumanc** [comment]
Hi, I was wondering if you made any progress on this issue? I am running into the same issues with the latest FBSimulatorControl and Xcode 9.4.1

**Comment by zeyadsalloum** [comment]
this should be fixed.
Also we just released idb. a new tool that improves significantly over fbsimctl. We recommend switching over. As part of our renewed commitment to this repo we are cleaning up old issues and will be monitoring and reviewing more closely from now on. if you still think this issue is relevant feel free to reopen

**Comment by lawrencelomax** [comment]
We now don't depend on the Xcode frameworks for app launching on Devices.

There are some limitations here, which involve provisioning profiles and dev builds so you may need to watch out for that.

**Comment by Usipov** [comment]
@lawrencelomax, can you share a  link to idb docs (especially to docs about running on real devices)?
Thanks in advance!
