### ISSUE TITLE
Brew install fbsimctl --HEAD failed on high sierra 10.13.6 with xcode 10 release version.

### ISSUE THREAD

**Issue by dakenico** [facebook/idb#491]
Followed the install steps and still got error:

the log below doesn't seem to show where the error happened:  unless I went into /User/me/Library/Logs/Homebrew/fbsimctl 

==> Installing fbsimctl from facebook/fb
==> Cloning https://github.com/facebook/FBSimulatorControl.git
Updating /Users/dchin/Library/Caches/Homebrew/fbsimctl--git
==> Checking out branch master
Already on 'master'
Your branch is up to date with 'origin/master'.
HEAD is now at 37cfbd0 Fix FBDeviceLogCommands
==> ./build.sh fbsimctl build /usr/local/Cellar/fbsimctl/HEAD-37cfbd0
Last 15 lines from /Users/dchin/Library/Logs/Homebrew/fbsimctl/01.build.sh:
    cd /tmp/fbsimctl-20180924-22757-17ldetz
    export LANG=en_US.US-ASCII
    clang -x objective-c -arch x86_64 -fmessage-length=0 -fdiagnostics-show-note-include-stack -fmacro-backtrace-limit=0 -std=gnu99 -fobjc-arc -fmodules -gmodules -fmodules-cache-path=/tmp/fbsimctl-20180924-22757-17ldetz/build/ModuleCache.noindex -fmodules-prune-interval=86400 -fmodules-prune-after=345600 -fbuild-session-file=/tmp/fbsimctl-20180924-22757-17ldetz/build/ModuleCache.noindex/Session.modulevalidation -fmodules-validate-once-per-build-session -Wnon-modular-include-in-framework-module -Werror=non-modular-include-in-framework-module -fmodule-name=FBControlCore -Wno-trigraphs -fpascal-strings -O0 -fno-common -Werror -Werror=incompatible-pointer-types -Werror=implicit-function-declaration -Wmissing-field-initializers -Wmissing-prototypes -Wdocumentation -Wunreachable-code -Wno-implicit-atomic-properties -Werror=deprecated-objc-isa-usage -Wno-objc-interface-ivars -Werror=objc-root-class -Wno-arc-repeated-use-of-weak -Wimplicit-retain-self -Wmissing-braces -Wparentheses -Wswitch -Wunused-function -Wunused-label -Wno-unused-parameter -Wunused-variable -Wunused-value -Wempty-body -Wuninitialized -Wconditional-uninitialized -Wunknown-pragmas -Wshadow -Wfour-char-constants -Wconversion -Wconstant-conversion -Wint-conversion -Wbool-conversion -Wenum-conversion -Wfloat-conversion -Wnon-literal-null-conversion -Wobjc-literal-conversion -Wsign-compare -Wshorten-64-to-32 -Wpointer-sign -Wnewline-eof -Wno-selector -Wno-strict-selector-match -Wundeclared-selector -Wdeprecated-implementations -DDEBUG=1 -DOBJC_OLD_DISPATCH_PROTOTYPES=0 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk -fasm-blocks -fstrict-aliasing -Wprotocol -Wdeprecated-declarations -mmacosx-version-min=10.10 -g -Wsign-conversion -Winfinite-recursion -Wcomma -Wblock-capture-autoreleasing -Wstrict-prototypes -Wno-semicolon-before-method-body -index-store-path /tmp/fbsimctl-20180924-22757-17ldetz/build/Index/DataStore -iquote /tmp/fbsimctl-20180924-22757-17ldetz/build/Build/Intermediates.noindex/FBSimulatorControl.build/Debug/FBControlCore.build/FBControlCore-generated-files.hmap -I/tmp/fbsimctl-20180924-22757-17ldetz/build/Build/Intermediates.noindex/FBSimulatorControl.build/Debug/FBControlCore.build/FBControlCore-own-target-headers.hmap -I/tmp/fbsimctl-20180924-22757-17ldetz/build/Build/Intermediates.noindex/FBSimulatorControl.build/Debug/FBControlCore.build/FBControlCore-all-non-framework-target-headers.hmap -ivfsoverlay /tmp/fbsimctl-20180924-22757-17ldetz/build/Build/Intermediates.noindex/FBSimulatorControl.build/Debug/FBControlCore.build/all-product-headers.yaml -iquote /tmp/fbsimctl-20180924-22757-17ldetz/build/Build/Intermediates.noindex/FBSimulatorControl.build/Debug/FBControlCore.build/FBControlCore-project-headers.hmap -I/tmp/fbsimctl-20180924-22757-17ldetz/build/Build/Products/Debug/include -I/tmp/fbsimctl-20180924-22757-17ldetz/PrivateHeaders -I/tmp/fbsimctl-20180924-22757-17ldetz/build/Build/Intermediates.noindex/FBSimulatorControl.build/Debug/FBControlCore.build/DerivedSources/x86_64 -I/tmp/fbsimctl-20180924-22757-17ldetz/build/Build/Intermediates.noindex/FBSimulatorControl.build/Debug/FBControlCore.build/DerivedSources -F/tmp/fbsimctl-20180924-22757-17ldetz/build/Build/Products/Debug -F/Applications/Xcode.app/Contents/Frameworks -F/Applications/Xcode.app/Contents/PlugIns -F/Applications/Xcode.app/Contents/OtherFrameworks -F/Applications/Xcode.app/Contents/SharedFrameworks -F/Applications/Xcode.app/Contents/Developer/Library/PrivateFrameworks -F/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/System/Library/PrivateFrameworks -F/Library/Developer/PrivateFrameworks -MMD -MT dependencies -MF /tmp/fbsimctl-20180924-22757-17ldetz/build/Build/Intermediates.noindex/FBSimulatorControl.build/Debug/FBControlCore.build/Objects-normal/x86_64/NSPredicate+FBControlCore.d --serialize-diagnostics /tmp/fbsimctl-20180924-22757-17ldetz/build/Build/Intermediates.noindex/FBSimulatorControl.build/Debug/FBControlCore.build/Objects-normal/x86_64/NSPredicate+FBControlCore.dia -c /tmp/fbsimctl-20180924-22757-17ldetz/FBControlCore/Utility/NSPredicate+FBControlCore.m -o /tmp/fbsimctl-20180924-22757-17ldetz/build/Build/Intermediates.noindex/FBSimulatorControl.build/Debug/FBControlCore.build/Objects-normal/x86_64/NSPredicate+FBControlCore.o

CompileC /tmp/fbsimctl-20180924-22757-17ldetz/build/Build/Intermediates.noindex/FBSimulatorControl.build/Debug/FBControlCore.build/Objects-normal/x86_64/FBiOSTargetStateUpdate.o /tmp/fbsimctl-20180924-22757-17ldetz/FBControlCore/Management/FBiOSTargetStateUpdate.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler (in target: FBControlCore)
    cd /tmp/fbsimctl-20180924-22757-17ldetz
    export LANG=en_US.US-ASCII
    clang -x objective-c -arch x86_64 -fmessage-length=0 -fdiagnostics-show-note-include-stack -fmacro-backtrace-limit=0 -std=gnu99 -fobjc-arc -fmodules -gmodules -fmodules-cache-path=/tmp/fbsimctl-20180924-22757-17ldetz/build/ModuleCache.noindex -fmodules-prune-interval=86400 -fmodules-prune-after=345600 -fbuild-session-file=/tmp/fbsimctl-20180924-22757-17ldetz/build/ModuleCache.noindex/Session.modulevalidation -fmodules-validate-once-per-build-session -Wnon-modular-include-in-framework-module -Werror=non-modular-include-in-framework-module -fmodule-name=FBControlCore -Wno-trigraphs -fpascal-strings -O0 -fno-common -Werror -Werror=incompatible-pointer-types -Werror=implicit-function-declaration -Wmissing-field-initializers -Wmissing-prototypes -Wdocumentation -Wunreachable-code -Wno-implicit-atomic-properties -Werror=deprecated-objc-isa-usage -Wno-objc-interface-ivars -Werror=objc-root-class -Wno-arc-repeated-use-of-weak -Wimplicit-retain-self -Wmissing-braces -Wparentheses -Wswitch -Wunused-function -Wunused-label -Wno-unused-parameter -Wunused-variable -Wunused-value -Wempty-body -Wuninitialized -Wconditional-uninitialized -Wunknown-pragmas -Wshadow -Wfour-char-constants -Wconversion -Wconstant-conversion -Wint-conversion -Wbool-conversion -Wenum-conversion -Wfloat-conversion -Wnon-literal-null-conversion -Wobjc-literal-conversion -Wsign-compare -Wshorten-64-to-32 -Wpointer-sign -Wnewline-eof -Wno-selector -Wno-strict-selector-match -Wundeclared-selector -Wdeprecated-implementations -DDEBUG=1 -DOBJC_OLD_DISPATCH_PROTOTYPES=0 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk -fasm-blocks -fstrict-aliasing -Wprotocol -Wdeprecated-declarations -mmacosx-version-min=10.10 -g -Wsign-conversion -Winfinite-recursion -Wcomma -Wblock-capture-autoreleasing -Wstrict-prototypes -Wno-semicolon-before-method-body -index-store-path /tmp/fbsimctl-20180924-22757-17ldetz/build/Index/DataStore -iquote /tmp/fbsimctl-20180924-22757-17ldetz/build/Build/Intermediates.noindex/FBSimulatorControl.build/Debug/FBControlCore.build/FBControlCore-generated-files.hmap -I/tmp/fbsimctl-20180924-22757-17ldetz/build/Build/Intermediates.noindex/FBSimulatorControl.build/Debug/FBControlCore.build/FBControlCore-own-target-headers.hmap -I/tmp/fbsimctl-20180924-22757-17ldetz/build/Build/Intermediates.noindex/FBSimulatorControl.build/Debug/FBControlCore.build/FBControlCore-all-non-framework-target-headers.hmap -ivfsoverlay /tmp/fbsimctl-20180924-22757-17ldetz/build/Build/Intermediates.noindex/FBSimulatorControl.build/Debug/FBControlCore.build/all-product-headers.yaml -iquote /tmp/fbsimctl-20180924-22757-17ldetz/build/Build/Intermediates.noindex/FBSimulatorControl.build/Debug/FBControlCore.build/FBControlCore-project-headers.hmap -I/tmp/fbsimctl-20180924-22757-17ldetz/build/Build/Products/Debug/include -I/tmp/fbsimctl-20180924-22757-17ldetz/PrivateHeaders -I/tmp/fbsimctl-20180924-22757-17ldetz/build/Build/Intermediates.noindex/FBSimulatorControl.build/Debug/FBControlCore.build/DerivedSources/x86_64 -I/tmp/fbsimctl-20180924-22757-17ldetz/build/Build/Intermediates.noindex/FBSimulatorControl.build/Debug/FBControlCore.build/DerivedSources -F/tmp/fbsimctl-20180924-22757-17ldetz/build/Build/Products/Debug -F/Applications/Xcode.app/Contents/Frameworks -F/Applications/Xcode.app/Contents/PlugIns -F/Applications/Xcode.app/Contents/OtherFrameworks -F/Applications/Xcode.app/Contents/SharedFrameworks -F/Applications/Xcode.app/Contents/Developer/Library/PrivateFrameworks -F/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/System/Library/PrivateFrameworks -F/Library/Developer/PrivateFrameworks -MMD -MT dependencies -MF /tmp/fbsimctl-20180924-22757-17ldetz/build/Build/Intermediates.noindex/FBSimulatorControl.build/Debug/FBControlCore.build/Objects-normal/x86_64/FBiOSTargetStateUpdate.d --serialize-diagnostics /tmp/fbsimctl-20180924-22757-17ldetz/build/Build/Intermediates.noindex/FBSimulatorControl.build/Debug/FBControlCore.build/Objects-normal/x86_64/FBiOSTargetStateUpdate.dia -c /tmp/fbsimctl-20180924-22757-17ldetz/FBControlCore/Management/FBiOSTargetStateUpdate.m -o /tmp/fbsimctl-20180924-22757-17ldetz/build/Build/Intermediates.noindex/FBSimulatorControl.build/Debug/FBControlCore.build/Objects-normal/x86_64/FBiOSTargetStateUpdate.o

** BUILD FAILED **

The following build commands failed:
	CompileC /tmp/fbsimctl-20180924-22757-17ldetz/build/Build/Intermediates.noindex/FBSimulatorControl.build/Debug/FBControlCore.build/Objects-normal/x86_64/FBBinaryParser.o /tmp/fbsimctl-20180924-22757-17ldetz/FBControlCore/Utility/FBBinaryParser.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)

, when I went in to this folder:  /Users/me/Library/Logs/Homebrew/fbsimctl/    I saw 01.build.sh .  and I opened it and saw 15 errors.  

at the top I saw:

 You don’t have permission to save the file “org.carthage.CarthageKit” in the folder “Caches”..

/usr/include/libxml2/module.modulemap:1:8: note: previously defined here
module libxml2 [system] [extern_c] {
       ^
1 error generated.
While building module 'Foundation' imported from /tmp/fbsimctl-20180924-22757-17ldetz/FBControlCore/Utility/FBBinaryParser.h:10:
While building module 'CoreFoundation' imported from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/Foundation.framework/Headers/Foundation.h:6:
While building module 'Dispatch' imported from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/CoreFoundation.framework/Headers/CFStream.h:20:
In file included from <module-includes>:1:
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/include/dispatch/dispatch.h:48:10: fatal error: could not build module 'os_object'
#include <os/object.h>
 ~~~~~~~~^
2 errors generated.
While building module 'Foundation' imported from /tmp/fbsimctl-20180924-22757-17ldetz/FBControlCore/Utility/FBBinaryParser.h:10:
While building module 'CoreFoundation' imported from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/Foundation.framework/Headers/Foundation.h:6:
In file included from <module-includes>:1:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/CoreFoundation.framework/Headers/CoreFoundation.h:60:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/CoreFoundation.framework/Headers/CFPropertyList.h:17:
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/CoreFoundation.framework/Headers/CFStream.h:20:10: fatal error: could not build module 'Dispatch'
#include <dispatch/dispatch.h>
 ~~~~~~~~^
3 errors generated.
While building module 'Foundation' imported from /tmp/fbsimctl-20180924-22757-17ldetz/FBControlCore/Utility/FBBinaryParser.h:10:
In file included from <module-includes>:1:
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/Foundation.framework/Headers/Foundation.h:6:10: fatal error: could not build module 'CoreFoundation'
#include <CoreFoundation/CoreFoundation.h>
 ~~~~~~~~^
While building module 'Foundation' imported from /tmp/fbsimctl-20180924-22757-17ldetz/FBControlCore/Utility/FBBinaryParser.h:10:
While building module 'CoreGraphics' imported from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSGeometry.h:12:
In file included from <module-includes>:1:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/CoreGraphics.framework/Headers/CoreGraphics.h:8:
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/CoreGraphics.framework/Headers/CGBase.h:12:10: fatal error: could not build module 'CoreFoundation'
#include <CoreFoundation/CFBase.h>
 ~~~~~~~~^
While building module 'Foundation' imported from /tmp/fbsimctl-20180924-22757-17ldetz/FBControlCore/Utility/FBBinaryParser.h:10:
While building module 'CoreGraphics' imported from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSGeometry.h:12:
While building module 'IOKit' imported from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/CoreGraphics.framework/Headers/CGDisplayConfiguration.h:12:
In file included from <module-includes>:4:
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/IOKit.framework/Headers/IOCFBundle.h:26:10: fatal error: could not build module 'CoreFoundation'
#include <CoreFoundation/CoreFoundation.h>
 ~~~~~~~~^
1 error generated.
2 errors generated.
While building module 'Foundation' imported from /tmp/fbsimctl-20180924-22757-17ldetz/FBControlCore/Utility/FBBinaryParser.h:10:
While building module 'Security' imported from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSURLCredential.h:9:
In file included from <module-includes>:1:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/Security.framework/Headers/Security.h:27:
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/Security.framework/Headers/SecBase.h:28:10: fatal error: could not build module 'CoreFoundation'
#include <CoreFoundation/CFBase.h>
 ~~~~~~~~^
1 error generated.
While building module 'Foundation' imported from /tmp/fbsimctl-20180924-22757-17ldetz/FBControlCore/Utility/FBBinaryParser.h:10:
While building module 'CoreServices' imported from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSURLError.h:17:
In file included from <module-includes>:1:
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/CoreServices.framework/Headers/CoreServices.h:19:10: fatal error: could not build module 'CoreFoundation'
#include <CoreFoundation/CoreFoundation.h>
 ~~~~~~~~^
While building module 'Foundation' imported from /tmp/fbsimctl-20180924-22757-17ldetz/FBControlCore/Utility/FBBinaryParser.h:10:
While building module 'CoreServices' imported from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSURLError.h:17:
While building module 'CFNetwork' imported from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/CoreServices.framework/Headers/CoreServices.h:35:
In file included from <module-includes>:1:
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/CFNetwork.framework/Headers/CFNetwork.h:18:10: fatal error: could not build module 'CoreFoundation'
#include <CoreFoundation/CoreFoundation.h>
 ~~~~~~~~^
 fatal error: could not build module 'CoreFoundation'
#include <CoreFoundation/CoreFoundation.h>
 ~~~~~~~~^
1 error generated.
While building module 'Foundation' imported from /tmp/fbsimctl-20180924-22757-17ldetz/FBControlCore/Utility/FBBinaryParser.h:10:
While building module 'CoreServices' imported from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSURLError.h:17:
While building module 'DiskArbitration' imported from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/CoreServices.framework/Frameworks/CarbonCore.framework/Headers/Files.h:56:
In file included from <module-includes>:1:
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/DiskArbitration.framework/Headers/DiskArbitration.h:27:10: fatal error: could not build module 'CoreFoundation'
#include <CoreFoundation/CoreFoundation.h>
 ~~~~~~~~^
1 error generated.
3 errors generated.
While building module 'Foundation' imported from /tmp/fbsimctl-20180924-22757-17ldetz/FBControlCore/Utility/FBBinaryParser.h:10:
While building module 'ApplicationServices' imported from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSAppleEventDescriptor.h:8:
In file included from <module-includes>:1:
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/ApplicationServices.framework/Headers/ApplicationServices.h:23:10: fatal error: could not build module 'CoreServices'
#include <CoreServices/CoreServices.h>
 ~~~~~~~~^
While building module 'Foundation' imported from /tmp/fbsimctl-20180924-22757-17ldetz/FBControlCore/Utility/FBBinaryParser.h:10:
While building module 'ApplicationServices' imported from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSAppleEventDescriptor.h:8:
While building module 'CoreText' imported from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/ApplicationServices.framework/Frameworks/ATS.framework/Headers/SFNTLayoutTypes.h:16:
In file included from <module-includes>:1:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/ApplicationServices.framework/Frameworks/CoreText.framework/Headers/CoreText.h:20:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/CoreText.framework/Headers/CTFont.h:20:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/CoreText.framework/Headers/CTFontDescriptor.h:20:
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/CoreText.framework/Headers/CTFontTraits.h:14:10: fatal error: could not build module 'CoreFoundation'
#include <CoreFoundation/CoreFoundation.h>
 ~~~~~~~~^
1 error generated.
While building module 'Foundation' imported from /tmp/fbsimctl-20180924-22757-17ldetz/FBControlCore/Utility/FBBinaryParser.h:10:
While building module 'ApplicationServices' imported from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSAppleEventDescriptor.h:8:

**Comment by ketanmujumdar** [comment]
👍

**Comment by ketanmujumdar** [comment]
I am getting a following error 

```
▸ Compiling FBAMDServiceConnection.m

❌  /Users/ketanmujumdar/FBSimulatorControl/FBDeviceControl/Management/FBAMDefines.h:49:3: pointer is missing a nullability type specifier (_Nonnull, _Nullable, or _Null_unspecified) [-Werror,-Wnullability-completeness]

  AMDeviceRef amDevice;
  ^


▸ Compiling FBDeviceControlError.m
▸ Compiling FBDeviceApplicationDataCommands.m

❌  /Users/ketanmujumdar/FBSimulatorControl/FBDeviceControl/Management/FBAMDefines.h:49:3: pointer is missing a nullability type specifier (_Nonnull, _Nullable, or _Null_unspecified) [-Werror,-Wnullability-completeness]

  AMDeviceRef amDevice;
  ^


▸ Compiling FBDeviceVideoFileEncoder.m
▸ Building FBSimulatorControl/FBSimulatorControl [Debug]
▸ Check Dependencies
▸ Compiling FBSimulatorXCTestProcessExecutor.m
▸ Compiling FBSimulatorTerminationStrategy.m
▸ Compiling FBSimulatorApplicationDataCommands.m
▸ Compiling FBUploadMediaStrategy.m
▸ Compiling FBSimulatorProcessFetcher.m
▸ Compiling FBSimulatorCrashLogCommands.m
▸ Compiling FBFramebuffer.m
** BUILD FAILED **


The following build commands failed:
	CompileC build/Build/Intermediates.noindex/FBSimulatorControl.build/Debug/FBDeviceControl.build/Objects-normal/x86_64/FBAMDServiceConnection.o FBDeviceControl/Management/FBAMDServiceConnection.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)
```

I am not sure why `pointer is missing a nullability type specifier`

Help Needed. 

Xcode version
```
Xcode 9.2
Build version 9C40b
```

**Comment by shane51** [comment]
same issue：
`Clang: 10.0 build 1000
Git: 2.19.0 => /usr/local/bin/git
Curl: 7.54.0 => /usr/bin/curl
Java: 1.8.0_181
macOS: 10.13.6-x86_64
CLT: 9.4.0.0.1.1526532315
Xcode: 10.0
`

**Comment by shane51** [comment]
update Mac os command line tool to newest version solved my issue. please have a try @dakenico

**Comment by ywongweb** [comment]
```
The following build commands failed:
        CompileC /tmp/fbsimctl-20181122-6031-o0k0jl/build/Build/Intermediates.noindex/FBSimulatorControl.build/Debug/FBSimulatorControl.build/Objects-normal/x86_64/FBSimulatorHIDEvent.o /tmp/fbsimctl-20181122-6031-o0k0jl/FBSimulatorControl/HID/FBSimulatorHIDEvent.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)
```

Getting a similar build error. 

```
Xcode 10.1
Build version 10B61
command line tools 10.1 10B61
```
`softwareupdate --list` shows everything is up to date
