### ISSUE TITLE
fbsimctl build fails in macOS 10.14.1 and Xcode 10.1 (HEAD@11d1c74)

### ISSUE THREAD

**Issue by olavoluissantos** [facebook/idb#502]
I have been trying to install fbsimctl without success. I ran 
`brew install fbsimctl --HEAD --verbose `
and build fails with the following last messages (the log was huge, I copied the part which fails)

CompileC /tmp/fbsimctl-20181128-81959-iuhgcj/build/Build/Intermediates.noindex/FBSimulatorControl.build/Debug/FBSimulatorControl.build/Objects-normal/x86_64/FBSimulatorHIDEvent.o /tmp/fbsimctl-20181128-81959-iuhgcj/FBSimulatorControl/HID/FBSimulatorHIDEvent.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler (in target: FBSimulatorControl)
    cd /tmp/fbsimctl-20181128-81959-iuhgcj
    export LANG=en_US.US-ASCII
    clang -x objective-c -arch x86_64 -fmessage-length=0 -fdiagnostics-show-note-include-stack -fmacro-backtrace-limit=0 -std=gnu99 -fobjc-arc -fmodules -gmodules -fmodules-cache-path=/tmp/fbsimctl-20181128-81959-iuhgcj/build/ModuleCache.noindex -fmodules-prune-interval=86400 -fmodules-prune-after=345600 -fbuild-session-file=/tmp/fbsimctl-20181128-81959-iuhgcj/build/ModuleCache.noindex/Session.modulevalidation -fmodules-validate-once-per-build-session -Wnon-modular-include-in-framework-module -Werror=non-modular-include-in-framework-module -fmodule-name=FBSimulatorControl -Wno-trigraphs -fpascal-strings -O0 -fno-common -Werror -Werror=incompatible-pointer-types -Werror=implicit-function-declaration -Wmissing-field-initializers -Wmissing-prototypes -Wdocumentation -Wunreachable-code -Wno-implicit-atomic-properties -Werror=deprecated-objc-isa-usage -Wno-objc-interface-ivars -Werror=objc-root-class -Wno-arc-repeated-use-of-weak -Wimplicit-retain-self -Wmissing-braces -Wparentheses -Wswitch -Wunused-function -Wunused-label -Wno-unused-parameter -Wunused-variable -Wunused-value -Wempty-body -Wuninitialized -Wconditional-uninitialized -Wunknown-pragmas -Wshadow -Wfour-char-constants -Wconversion -Wconstant-conversion -Wint-conversion -Wbool-conversion -Wenum-conversion -Wfloat-conversion -Wnon-literal-null-conversion -Wobjc-literal-conversion -Wsign-compare -Wshorten-64-to-32 -Wpointer-sign -Wnewline-eof -Wno-selector -Wno-strict-selector-match -Wundeclared-selector -Wdeprecated-implementations -DDEBUG=1 -DOBJC_OLD_DISPATCH_PROTOTYPES=0 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk -fasm-blocks -fstrict-aliasing -Wprotocol -Wdeprecated-declarations -mmacosx-version-min=10.10 -g -Wsign-conversion -Winfinite-recursion -Wcomma -Wblock-capture-autoreleasing -Wstrict-prototypes -Wno-semicolon-before-method-body -index-store-path /tmp/fbsimctl-20181128-81959-iuhgcj/build/Index/DataStore -iquote /tmp/fbsimctl-20181128-81959-iuhgcj/build/Build/Intermediates.noindex/FBSimulatorControl.build/Debug/FBSimulatorControl.build/FBSimulatorControl-generated-files.hmap -I/tmp/fbsimctl-20181128-81959-iuhgcj/build/Build/Intermediates.noindex/FBSimulatorControl.build/Debug/FBSimulatorControl.build/FBSimulatorControl-own-target-headers.hmap -I/tmp/fbsimctl-20181128-81959-iuhgcj/build/Build/Intermediates.noindex/FBSimulatorControl.build/Debug/FBSimulatorControl.build/FBSimulatorControl-all-non-framework-target-headers.hmap -ivfsoverlay /tmp/fbsimctl-20181128-81959-iuhgcj/build/Build/Intermediates.noindex/FBSimulatorControl.build/Debug/FBSimulatorControl.build/all-product-headers.yaml -iquote /tmp/fbsimctl-20181128-81959-iuhgcj/build/Build/Intermediates.noindex/FBSimulatorControl.build/Debug/FBSimulatorControl.build/FBSimulatorControl-project-headers.hmap -I/tmp/fbsimctl-20181128-81959-iuhgcj/build/Build/Products/Debug/include -I/tmp/fbsimctl-20181128-81959-iuhgcj/PrivateHeaders -I/tmp/fbsimctl-20181128-81959-iuhgcj/build/Build/Intermediates.noindex/FBSimulatorControl.build/Debug/FBSimulatorControl.build/DerivedSources/x86_64 -I/tmp/fbsimctl-20181128-81959-iuhgcj/build/Build/Intermediates.noindex/FBSimulatorControl.build/Debug/FBSimulatorControl.build/DerivedSources -F/tmp/fbsimctl-20181128-81959-iuhgcj/build/Build/Products/Debug -F/Applications/Xcode.app/Contents/Frameworks -F/Applications/Xcode.app/Contents/PlugIns -F/Applications/Xcode.app/Contents/OtherFrameworks -F/Applications/Xcode.app/Contents/SharedFrameworks -F/Applications/Xcode.app/Contents/Developer/Library/PrivateFrameworks -F/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/System/Library/PrivateFrameworks -F/Library/Developer/PrivateFrameworks -MMD -MT dependencies -MF /tmp/fbsimctl-20181128-81959-iuhgcj/build/Build/Intermediates.noindex/FBSimulatorControl.build/Debug/FBSimulatorControl.build/Objects-normal/x86_64/FBSimulatorHIDEvent.d --serialize-diagnostics /tmp/fbsimctl-20181128-81959-iuhgcj/build/Build/Intermediates.noindex/FBSimulatorControl.build/Debug/FBSimulatorControl.build/Objects-normal/x86_64/FBSimulatorHIDEvent.dia -c /tmp/fbsimctl-20181128-81959-iuhgcj/FBSimulatorControl/HID/FBSimulatorHIDEvent.m -o /tmp/fbsimctl-20181128-81959-iuhgcj/build/Build/Intermediates.noindex/FBSimulatorControl.build/Debug/FBSimulatorControl.build/Objects-normal/x86_64/FBSimulatorHIDEvent.o
/tmp/fbsimctl-20181128-81959-iuhgcj/FBSimulatorControl/HID/FBSimulatorHIDEvent.m
:
566
:
10
:
 
error
: 
implicit conversion turns floating-point number into integer: 'double' to 'NSUInteger' (aka 'unsigned long') [-Werror,-Wfloat-conversion]

  return self.duration;

  ~~~~~~ ^~~~~~~~~~~~~

1 error generated.

CompileC /tmp/fbsimctl-20181128-81959-iuhgcj/build/Build/Intermediates.noindex/FBSimulatorControl.build/Debug/FBSimulatorControl.build/Objects-normal/x86_64/FBSimulatorHID.o /tmp/fbsimctl-20181128-81959-iuhgcj/FBSimulatorControl/HID/FBSimulatorHID.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler (in target: FBSimulatorControl)
    cd /tmp/fbsimctl-20181128-81959-iuhgcj
    export LANG=en_US.US-ASCII
    clang -x objective-c -arch x86_64 -fmessage-length=0 -fdiagnostics-show-note-include-stack -fmacro-backtrace-limit=0 -std=gnu99 -fobjc-arc -fmodules -gmodules -fmodules-cache-path=/tmp/fbsimctl-20181128-81959-iuhgcj/build/ModuleCache.noindex -fmodules-prune-interval=86400 -fmodules-prune-after=345600 -fbuild-session-file=/tmp/fbsimctl-20181128-81959-iuhgcj/build/ModuleCache.noindex/Session.modulevalidation -fmodules-validate-once-per-build-session -Wnon-modular-include-in-framework-module -Werror=non-modular-include-in-framework-module -fmodule-name=FBSimulatorControl -Wno-trigraphs -fpascal-strings -O0 -fno-common -Werror -Werror=incompatible-pointer-types -Werror=implicit-function-declaration -Wmissing-field-initializers -Wmissing-prototypes -Wdocumentation -Wunreachable-code -Wno-implicit-atomic-properties -Werror=deprecated-objc-isa-usage -Wno-objc-interface-ivars -Werror=objc-root-class -Wno-arc-repeated-use-of-weak -Wimplicit-retain-self -Wmissing-braces -Wparentheses -Wswitch -Wunused-function -Wunused-label -Wno-unused-parameter -Wunused-variable -Wunused-value -Wempty-body -Wuninitialized -Wconditional-uninitialized -Wunknown-pragmas -Wshadow -Wfour-char-constants -Wconversion -Wconstant-conversion -Wint-conversion -Wbool-conversion -Wenum-conversion -Wfloat-conversion -Wnon-literal-null-conversion -Wobjc-literal-conversion -Wsign-compare -Wshorten-64-to-32 -Wpointer-sign -Wnewline-eof -Wno-selector -Wno-strict-selector-match -Wundeclared-selector -Wdeprecated-implementations -DDEBUG=1 -DOBJC_OLD_DISPATCH_PROTOTYPES=0 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk -fasm-blocks -fstrict-aliasing -Wprotocol -Wdeprecated-declarations -mmacosx-version-min=10.10 -g -Wsign-conversion -Winfinite-recursion -Wcomma -Wblock-capture-autoreleasing -Wstrict-prototypes -Wno-semicolon-before-method-body -index-store-path /tmp/fbsimctl-20181128-81959-iuhgcj/build/Index/DataStore -iquote /tmp/fbsimctl-20181128-81959-iuhgcj/build/Build/Intermediates.noindex/FBSimulatorControl.build/Debug/FBSimulatorControl.build/FBSimulatorControl-generated-files.hmap -I/tmp/fbsimctl-20181128-81959-iuhgcj/build/Build/Intermediates.noindex/FBSimulatorControl.build/Debug/FBSimulatorControl.build/FBSimulatorControl-own-target-headers.hmap -I/tmp/fbsimctl-20181128-81959-iuhgcj/build/Build/Intermediates.noindex/FBSimulatorControl.build/Debug/FBSimulatorControl.build/FBSimulatorControl-all-non-framework-target-headers.hmap -ivfsoverlay /tmp/fbsimctl-20181128-81959-iuhgcj/build/Build/Intermediates.noindex/FBSimulatorControl.build/Debug/FBSimulatorControl.build/all-product-headers.yaml -iquote /tmp/fbsimctl-20181128-81959-iuhgcj/build/Build/Intermediates.noindex/FBSimulatorControl.build/Debug/FBSimulatorControl.build/FBSimulatorControl-project-headers.hmap -I/tmp/fbsimctl-20181128-81959-iuhgcj/build/Build/Products/Debug/include -I/tmp/fbsimctl-20181128-81959-iuhgcj/PrivateHeaders -I/tmp/fbsimctl-20181128-81959-iuhgcj/build/Build/Intermediates.noindex/FBSimulatorControl.build/Debug/FBSimulatorControl.build/DerivedSources/x86_64 -I/tmp/fbsimctl-20181128-81959-iuhgcj/build/Build/Intermediates.noindex/FBSimulatorControl.build/Debug/FBSimulatorControl.build/DerivedSources -F/tmp/fbsimctl-20181128-81959-iuhgcj/build/Build/Products/Debug -F/Applications/Xcode.app/Contents/Frameworks -F/Applications/Xcode.app/Contents/PlugIns -F/Applications/Xcode.app/Contents/OtherFrameworks -F/Applications/Xcode.app/Contents/SharedFrameworks -F/Applications/Xcode.app/Contents/Developer/Library/PrivateFrameworks -F/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/System/Library/PrivateFrameworks -F/Library/Developer/PrivateFrameworks -MMD -MT dependencies -MF /tmp/fbsimctl-20181128-81959-iuhgcj/build/Build/Intermediates.noindex/FBSimulatorControl.build/Debug/FBSimulatorControl.build/Objects-normal/x86_64/FBSimulatorHID.d --serialize-diagnostics /tmp/fbsimctl-20181128-81959-iuhgcj/build/Build/Intermediates.noindex/FBSimulatorControl.build/Debug/FBSimulatorControl.build/Objects-normal/x86_64/FBSimulatorHID.dia -c /tmp/fbsimctl-20181128-81959-iuhgcj/FBSimulatorControl/HID/FBSimulatorHID.m -o /tmp/fbsimctl-20181128-81959-iuhgcj/build/Build/Intermediates.noindex/FBSimulatorControl.build/Debug/FBSimulatorControl.build/Objects-normal/x86_64/FBSimulatorHID.o

** BUILD FAILED **


The following build commands failed:
	CompileC /tmp/fbsimctl-20181128-81959-iuhgcj/build/Build/Intermediates.noindex/FBSimulatorControl.build/Debug/FBSimulatorControl.build/Objects-normal/x86_64/FBSimulatorHIDEvent.o /tmp/fbsimctl-20181128-81959-iuhgcj/FBSimulatorControl/HID/FBSimulatorHIDEvent.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)

==> Formula
Tap: facebook/fb
Path: /usr/local/Homebrew/Library/Taps/facebook/homebrew-fb/fbsimctl.rb
==> Configuration
HOMEBREW_VERSION: 1.8.4
ORIGIN: https://github.com/Homebrew/brew
HEAD: 2063a8a4d849b00f279ee2dd26e9f38745382ffc
Last commit: 4 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 1d4f1d5602eac539f4c02b4a82f78b3a3ed5413f
Core tap last commit: 42 minutes ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_ENABLE_AUTO_UPDATE_MIGRATION: 1
CPU: dual-core 64-bit haswell
Homebrew Ruby: 2.3.7 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/bin/ruby
Clang: 10.0 build 1000
Git: 2.17.2 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Curl: 7.54.0 => /usr/bin/curl
macOS: 10.14.1-x86_64
CLT: 10.1.0.0.1.1539992718
Xcode: 10.1
==> ENV
HOMEBREW_CC: clang
HOMEBREW_CXX: clang++
MAKEFLAGS: -j2
CMAKE_PREFIX_PATH: /usr/local
CMAKE_INCLUDE_PATH: /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/include/libxml2:/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers
CMAKE_LIBRARY_PATH: /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/OpenGL.framework/Versions/Current/Libraries
CMAKE_FRAMEWORK_PATH: /usr/local/opt/carthage/Frameworks
PKG_CONFIG_LIBDIR: /usr/lib/pkgconfig:/usr/local/Homebrew/Library/Homebrew/os/mac/pkgconfig/10.14
HOMEBREW_GIT: git
HOMEBREW_SDKROOT: /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk
ACLOCAL_PATH: /usr/local/share/aclocal
PATH: /usr/local/Homebrew/Library/Homebrew/shims/mac/super:/usr/local/opt/carthage/bin:/usr/bin:/bin:/usr/sbin:/sbin

**Comment by derline** [comment]
similar question

**Comment by santiagofm** [comment]
This gets fixed with #500, don't know why it's not merged yet 😕

**Comment by sbmehdy** [comment]
Agreeing with @warent. Any chance this will get merged ? 
I encounter the same issue and would love to be able to use `fbsimctl`!

**Comment by 812865052** [comment]
I encounter the same issue

**Comment by 812865052** [comment]
I solve the problem. https://github.com/facebook/FBSimulatorControl/blob/master/fbsimctl/Documentation/Installation.md this page introduce Custom Installation. you can download zip source code, then build manually and excute ./output/fbsimctl list. if no error,you can use ln to link your ./output/fbsimctl to /usr/bin or something like ~/Library/Python/2.7/bin/fbsimctl. it is work for me.

**Comment by SirCYong** [comment]
==> ./build.sh fbsimctl build /usr/local/Cellar/fbsimctl/HEAD-68f8395
using target fbsimctl
using command build
using output directory /usr/local/Cellar/fbsimctl/HEAD-68f8395
/usr/local/opt/carthage/bin/carthage
/private/tmp/fbsimctl-20190320-38524-1bneg42/fbsimctl /private/tmp/fbsimctl-20190320-38524-1bneg42
2019-03-20 15:23:41.429 carthage[38800:272952] NetworkStorageDB:_openDBReadConnections: failed to open read connection to DB @ /Users/caoyong/Library/Caches/carthage/Cache.db.  Error=14. Cause=unable to open database file
2019-03-20 15:23:41.429 carthage[38800:272952] CacheRead: unable to open cache files in /Users/caoyong/Library/Caches/carthage
2019-03-20 15:23:42.104 carthage[38800:272952] Warning: No Caches directory could be found or created: You don’t have permission to save the file “org.carthage.CarthageKit” in the folder “Caches”.. (Error Domain=NSCocoaErrorDomain Code=513 "You don’t have permission to save the file “org.carthage.CarthageKit” in the folder “Caches”." UserInfo={NSFilePath=/Users/caoyong/Library/Caches/org.carthage.CarthageKit, NSUnderlyingError=0x7fe654528c00 {Error Domain=NSPOSIXErrorDomain Code=1 "Operation not permitted"}})
*** Checking out GCDWebServer at "3.3.3"
*** Cloning GCDWebServer




Please help me solve this problem

**Comment by 812865052** [comment]
> ==> ./build.sh fbsimctl build /usr/local/Cellar/fbsimctl/HEAD-68f8395
> using target fbsimctl
> using command build
> using output directory /usr/local/Cellar/fbsimctl/HEAD-68f8395
> /usr/local/opt/carthage/bin/carthage
> /private/tmp/fbsimctl-20190320-38524-1bneg42/fbsimctl /private/tmp/fbsimctl-20190320-38524-1bneg42
> 2019-03-20 15:23:41.429 carthage[38800:272952] NetworkStorageDB:_openDBReadConnections: failed to open read connection to DB @ /Users/caoyong/Library/Caches/carthage/Cache.db. Error=14. Cause=unable to open database file
> 2019-03-20 15:23:41.429 carthage[38800:272952] CacheRead: unable to open cache files in /Users/caoyong/Library/Caches/carthage
> 2019-03-20 15:23:42.104 carthage[38800:272952] Warning: No Caches directory could be found or created: You don’t have permission to save the file “org.carthage.CarthageKit” in the folder “Caches”.. (Error Domain=NSCocoaErrorDomain Code=513 "You don’t have permission to save the file “org.carthage.CarthageKit” in the folder “Caches”." UserInfo={NSFilePath=/Users/caoyong/Library/Caches/org.carthage.CarthageKit, NSUnderlyingError=0x7fe654528c00 {Error Domain=NSPOSIXErrorDomain Code=1 "Operation not permitted"}})
> *** Checking out GCDWebServer at "3.3.3"
> *** Cloning GCDWebServer
> 
> Please help me solve this problem。**How to give it permission？**

the easiest way is I give you my build package，it is work for my colleague。

**Comment by zeyadsalloum** [comment]
We just released idb. a new tool that improves significantly over fbsimctl. We recommend switching over. As part of our renewed commitment to this repo we are cleaning up old issues and will be monitoring and reviewing more closely from now on. if you still think this issue is relevant feel free to reopen

**Comment by zeyadsalloum** [comment]
We just released idb. a new tool that improves significantly over fbsimctl. We recommend switching over. As part of our renewed commitment to this repo we are cleaning up old issues and will be monitoring and reviewing more closely from now on. if you still think this issue is relevant feel free to reopen
