### ISSUE TITLE
Coordinates in set_location don't match

### ISSUE THREAD

**Issue by ayelenmarie** [facebook/idb#512]
I tried to set a custom location in my iPhone X Simulator with 
`fbsimctl 238EA766-EDB0-440F-BF3F-3C97C0362869 set_location 32.0853 34.7818`

but I get this error 

`'["238EA766-EDB0-440F-BF3F-3C97C0362869", "set_location", "32.0853", "34.7818"]' does not match '[fbsimctl print [action]`

I tried switching the dots by commas but neither worked, I still get the same error.
I installed `fbsimctl` via Homebrew with `--HEAD`, as doing it without it didn't work.

**Comment by zeyadsalloum** [comment]
closing this as it should be fixed if you switch to using idb instead of fbsimctl

**Comment by tayyab-sarwar** [comment]
@ayelenmarie did you able to resolve this issue?

**Comment by ayelenmarie** [comment]
@tayyab-sarwar not yet, I submitted a request enhancement (which was accepted) in Detox's repo so they can implement it. Once that is done, I will be able to try it in my testing build.

**Comment by ayelenmarie** [comment]
@tayyab-sarwar I've tried using `idb` and encountered an issue I commented on #523.

**Comment by pavlo-paliychuk-insighty** [comment]
@ayelenmarie any progress? struggling with the same thing on bitrise

**Comment by ayelenmarie** [comment]
Hey @pavlo-paliychuk-insighty, `fbsimctl` is deprecated now and part of the new `idb`, which has another sintax to set a location. In this issue on Detox repo [https://github.com/wix/Detox/issues/1371](url) we discuss some points about it. Even though we haven't cracked it entirely, maybe something in there can help you!
