### ISSUE TITLE
Question: running tests on real devices using fbxctest

### ISSUE THREAD

**Issue by Usipov** [facebook/idb#515]
Following **xcodebuild** example I tried to run latest **fbxctest** on real devices like this:
```
${pathToFbxctest}/fbxctest \
run-tests \
-sdk iphoneos \
-destination "id=793e46c380b7250ee7295dbe0adcdff4fe9bcdd9" \
-only ${pathToXctestBundle}:TestClass/testMethod \
-appTest ${pathToXctestBundle}:${pathToApp}
```

However, **fbxctest** does not support destinations starting with **id** (`"id=793e46c380b7250ee7295dbe0adcdff4fe9bcdd9"`).

I found some related issues using **Buck** or **WebDriverAgent** to run tests on real devices, but they were not very useful. 

I took a look at the source files of **fbxctest** and found only **macosx** and **iphonesimulator** destinations.

So it looks like real devices are not supported. Or are they?

Thanks in advance

**Comment by beefon** [comment]
fbxctest does not support real devices at all.

**Comment by Usipov** [comment]
@beefon, thanks!

**Comment by lawrencelomax** [comment]
`fbxctest` doesn't support real devices. However, we do run tests on devices using `idb`.

Going forward we want to help people run this flow via `idb` on devices.

If there's anything that's missing here or problems that you are having with `idb` on devices, please let us know.
