### ISSUE TITLE
[Question] How to show userdefaults file? 

### ISSUE THREAD

**Issue by techinpark** [facebook/idb#517]
I want to know  how to show userdefaults objects using idb??
Thanks.

**Comment by c-ryan747** [comment]
Looking at https://stackoverflow.com/a/1677104 it appears that user defaults are stored under `Library/Preferences` in each apps data container

So you can use the `file` commands to read or write the file:
`idb file pull --bundle-id XXX Library/Preferences/XXX.plist local.plist`
`idb file push --bundle-id XXX local.plist Library/Preferences/XXX.plist`

**Comment by techinpark** [comment]
@c-ryan747 Thanks a lot
