### ISSUE TITLE
'DebugServerRequest' object is not subscriptable

### ISSUE THREAD

**Issue by skiluo** [facebook/idb#521]
run
idb debugserver start --udid a66b557b4b3129a337c5742e9b57325df8548f3b --json com.uhome.haier.Uplus
return 'DebugServerRequest' object is not subscriptable

it seems that DebugServerRequest is not stream in idb.proto

**Comment by c-ryan747** [comment]
Sorry we must have broke this when making a change last week to the deamons implementation. I'll get a fix out today
