### ISSUE TITLE
Need guide how to connect to real device.

### ISSUE THREAD

**Issue by codeskyblue** [facebook/idb#533]
## Description
In the documentation described in fbidb.io, it says support real device.

When I connect my iPhone to my Mac, I can see my device from `idevice_id -l` but can not see device from `idb list-targets`

### Additional Information
I try to run the following command

```
idb connect 539c5fffb18f2be0bf7f771d68f7c327fb68d3d1
provide either a UDID or the host and port of the companion
```

Please help.

**Comment by flasco** [comment]
need help too

**Comment by flasco** [comment]
I can see my device in `list-targets`, can screenshot, but can't connect, it will throw `provide either a UDID or the host and port of the companion` when I try to run `idb connect [udid]`

**Comment by c-ryan747** [comment]
I think theres a handful of issues going on here that are causing this:

1. idb doesn't pick up on new devices once the idb daemon has been started.
2. `idb connect UDID` only works if the daemon knows about the device, and it gives a rather cryptic error message if not.

The easiest workarounds for now are probably either:
- Kill all idb processes, plug in your phone, then run `idb list-targets`
- Start a companion manually `idb_companion --udid UDID --grpc-port XXXX` then connect to it with `idb connect localhost XXXX`

**Comment by flasco** [comment]
I did it according to the instructions you give, but it can't work, any suggestions? @c-ryan747 

#### instruct
```bash
StarrySky:~ czq$ idb connect localhost 9182
udid: ddd871b02775cdb6c3b40872d17d41f66436c56b is_local: True
StarrySky:~ czq$ idb launch [bundle id]
Connection was closed
StarrySky:~ czq$ idb ui tap 600 700
Connection was closed
```
#### idb_companion

```bash
I0611 21:41:49.779364000 123145396076544 ev_posix.cc:253]              (fd-trace) fd_create(7, tcp-server-connection:ipv6:[::1]:59144, 1)
I0611 21:41:49.779465000 123145396076544 connectivity_state.cc:116]    CONWATCH: 0x7f949007eaa8 server_transport: from IDLE [cur=READY] notify=0x7f948f5716a8
I0611 21:41:49.779477000 123145396076544 connectivity_state.cc:116]    CONWATCH: 0x7f949007eaa8 server_transport: from READY [cur=READY] notify=0x7f948f5716a8
2019-06-11 21:41:49.781+0800 New Error Built ==> Error Domain=com.facebook.idb Code=0 "Target doesn't conform to FBSimulatorLifecycleCommands protocol ddd871b02775cdb6c3b40872d17d41f66436c56b | Forever  | Booted | iPhone 6 Plus | iOS 12.1 | arm64 | 0 | 0" UserInfo={NSLocalizedDescription=Target doesn't conform to FBSimulatorLifecycleCommands protocol ddd871b02775cdb6c3b40872d17d41f66436c56b | Forever  | Booted | iPhone 6 Plus | iOS 12.1 | arm64 | 0 | 0}
D0611 21:41:49.781074000 123145396076544 call.cc:722]                  set_final_status SVR
D0611 21:41:49.781091000 123145396076544 call.cc:723]                  "No Error"
I0611 21:41:49.781765000 123145396076544 connectivity_state.cc:164]    SET: 0x7f949007eaa8 server_transport: READY --> SHUTDOWN [close_transport] error=0x7f948f4101e0 {"created":"@1560260509.781739000","description":"Endpoint read failed","file":"src/core/ext/transport/chttp2/transport/chttp2_transport.cc","file_line":2500,"occurred_during_write":0,"referenced_errors":[{"created":"@1560260509.781736000","description":"Socket closed","fd":7,"file":"src/core/lib/iomgr/tcp_posix.cc","file_line":479,"grpc_status":14,"target_address":"ipv6:[::1]:59144"}]}
I0611 21:41:49.781781000 123145396076544 connectivity_state.cc:190]    NOTIFY: 0x7f949007eaa8 server_transport: 0x7f948f5716a8
I0611 21:41:49.781789000 123145396076544 ev_posix.cc:273]              (fd-trace) fd_shutdown(7)
I0611 21:41:49.781813000 123145396076544 ev_posix.cc:266]              (fd-trace) grpc_fd_orphan, fd:7 closed

```

**Comment by c-ryan747** [comment]
Based on trying this locally for `idb launch` i see
```
cannot be launched as it's not signed with a development identity
```
Are you trying to launch an app you've signed yourself?

The error message you linked is for `ui tap` as this command is not supported on devices. It appears that we're swallowing the error message for it at some point though.

---

I've got a fix ready for the daemon not being notified about new devices, should hopefully be on master in a day or two

**Comment by flasco** [comment]
my device is iPhone 6 Plus, which real devices support `ui` commands?

and the app I tried to launch was downloaded from the app store, not developed by myself.

**Comment by c-ryan747** [comment]
Due to how locked down iOS devices are, it's not possible for us to offer the full range of commands idb supports for simulators.

I'd expect these commands to work on devices:
```
debugserver
install
instruments
launch
list-apps
crash
log
pull
push
record
xctest
uninstall
```
however some of them might be a bit more restricted than the simulator versions e.g. launch only works with developer signed apps

**Comment by EraChen233** [comment]
@codeskyblue 
try 
```
idb kill 
```
and rerun
```
idb list-targets
```

I have the same problem and this works for me.

**Comment by zeyadsalloum** [comment]
**idb kill** is a good cleanup mechanism if idb starts misbehaving in any way. i'm currently working on improving the core of idb that leads to it misbehaving sometimes.
