### ISSUE TITLE
'idb launch' support for app_environments

### ISSUE THREAD

**Issue by YurRee** [facebook/idb#535]
### Description

Hi, How can I pass environment variables of apps to the simulator when using `idb launch`?

### Reproduction

Only bundle_id and app_arguments, are required, but how can I pass app_environments?
```
▶ idb launch
usage: idb launch [-h] [-f] [-w] [--udid UDID] [--daemon-host DAEMON_HOST]
                  [--force] [--daemon-grpc-port DAEMON_GRPC_PORT]
                  [--log {DEBUG,INFO,WARNING,ERROR,CRITICAL}] [--json]
                  bundle_id ...
idb launch: error: the following arguments are required: bundle_id, app_arguments
```

### Solution

With `WebDriverAgent` I used to do like this:
```
curl -X POST \
  http://host:port/session/ \
  -H 'Content-Type: application/json' \
  -H 'cache-control: no-cache' \
  -d '{
    "desiredCapabilities": {
        "bundleId": "com.my.bundleId",
        "arguments": [],
        "environment": {
            "envKey": "enValue",
            ...
        },
        "eventloopIdleDelaySec": 0,
        "shouldWaitForQuiescence": true,
        "shouldUseTestManagerForVisibilityDetection": false,
        "maxTypingFrequency": 60,
        "shouldUseSingletonTestManager": true
    }
}'
```

### Additional Information

* `idb` revision: 0.0.6

**Comment by c-ryan747** [comment]
`idb launch` along with `idb xctest run` will pass through any environment variables to the launched process that are prefixed with `IDB_`

idb will remove the prefix before passing them through so
```
IDB_X=123 idb launch YYY
```
will launch YYY with X=123 in the environment

**Comment by phoebusliang** [comment]
> ### Description
> Hi, How can I pass environment variables of apps to the simulator when using `idb launch`?
> 
> ### Reproduction
> Only bundle_id and app_arguments, are required, but how can I pass app_environments?
> 
> ```
> ▶ idb launch
> usage: idb launch [-h] [-f] [-w] [--udid UDID] [--daemon-host DAEMON_HOST]
>                   [--force] [--daemon-grpc-port DAEMON_GRPC_PORT]
>                   [--log {DEBUG,INFO,WARNING,ERROR,CRITICAL}] [--json]
>                   bundle_id ...
> idb launch: error: the following arguments are required: bundle_id, app_arguments
> ```
> 
> ### Solution
> With `WebDriverAgent` I used to do like this:
> 
> ```
> curl -X POST \
>   http://host:port/session/ \
>   -H 'Content-Type: application/json' \
>   -H 'cache-control: no-cache' \
>   -d '{
>     "desiredCapabilities": {
>         "bundleId": "com.my.bundleId",
>         "arguments": [],
>         "environment": {
>             "envKey": "enValue",
>             ...
>         },
>         "eventloopIdleDelaySec": 0,
>         "shouldWaitForQuiescence": true,
>         "shouldUseTestManagerForVisibilityDetection": false,
>         "maxTypingFrequency": 60,
>         "shouldUseSingletonTestManager": true
>     }
> }'
> ```
> 
> ### Additional Information
> * `idb` revision: 0.0.6

I want to know where we can find the host and port from idb? Just like you mentioned, I used WDA and can easy to monitor the host and port, but if we use the idb is the alternative, where and how we find the host and port for the launched devices/simulator?
