### ISSUE TITLE
can't install fbsimctl due to build failures

### ISSUE THREAD

**Issue by sugago** [facebook/idb#536]
Build fails whenever I try installing fbsimctl (HEAD@6993a6b).

Error:
```
The following build commands failed:
	CompileSwift normal x86_64 /tmp/fbsimctl-20190703-4686-1awxyrz/fbsimctl/FBSimulatorControlKit/Swift/Parser.swift
	CompileSwiftSources normal x86_64 com.apple.xcode.tools.swift.compiler
(2 failures)
```

Xcode version:
```
xcodebuild -version
Xcode 10.2.1
Build version 10E1001
```

**Comment by yogeshthanvi** [comment]
Same here

**Comment by zeyadsalloum** [comment]
sorry about that. I will look into this. Can you in the meantime try using idb ? we are not actively working on fbsimctl anymore.

**Comment by zeyadsalloum** [comment]
fixed in https://github.com/facebook/idb/commit/fb1bc18263fb2b2187a50629e5bf30a46b60be72
