### ISSUE TITLE
json output produces wrong structure

### ISSUE THREAD

**Issue by umutuzgur** [facebook/idb#544]
### Description

I installed 2 xctest bundles to the phone and then called `idb xctest list --json`. As an output, I got the following below instead of an array

{"bundle_id": "com.testUITests", "name": "testUITests", "architectures": ["x86_64"]}
{"bundle_id": "com.facebook.wda.runner", "name": "WebDriverAgentRunner", "architectures": ["x86_64"]}

### Reproduction

Install multiple xctest bundles on a simulator and list them

### Solution

We should return an array instead of 2 objects

### Additional Information

* `idb` revision: HEAD-5c6f53c

**Comment by zeyadsalloum** [comment]
the problem here is that we need to be careful when changing the output of idb as it will break any system that depends on it. we can add a new flag that changes the output. would you like to attempt the fix?

**Comment by umutuzgur** [comment]
@zeyadsalloum I can give it a try but I don't agree that we should create a new parameter. I get that it would break stuff but I believe that we should still use `--json` and maybe do a minor or major release so people can expect a breaking change
