### ISSUE TITLE
[Question] Can IDB works with WDA?

### ISSUE THREAD

**Issue by phoebusliang** [facebook/idb#566]
Previously, I used the fbsimctl to lunch the simulator/real devices with specific ports as parallel. And then using capsulate webdriveragent with different languages in projects. But now we just can use idb in the command line, actually, it's easier to use but not very powerful for setting up an automation project as engineering level.

My question is, can we combine idb with wda to make the automation project more flexible?

**Comment by simoreira** [comment]
Any updates?

**Comment by gyyfifafans** [comment]
same questions

**Comment by c-ryan747** [comment]
We have no plans to combine idb and WDA
