### ISSUE TITLE
idb_companion segmented fault

### ISSUE THREAD

**Issue by KPR7168** [facebook/idb#578]
### Description

I'm really new to this thing, please help me out. I'm trying to run ```idb_companion --udid 56A9B827-0437-4A5C-9350-1FFD9FF7AC19``` and it says ```[1]    12605 segmentation fault  idb_companion --udid 56A9B827-0437-4A5C-9350-1FFD9FF7AC19```

![image](https://user-images.githubusercontent.com/5600349/72254651-d8c48080-3658-11ea-95d4-a8760019023a.png)

### Additional Information
![image](https://user-images.githubusercontent.com/5600349/72254813-3a84ea80-3659-11ea-91b2-8339c791e272.png)
![image](https://user-images.githubusercontent.com/5600349/72254846-4d97ba80-3659-11ea-9bb5-e7a3d4462645.png)

**Comment by salphaon** [comment]
@KPR7168 
It seems that grpc 1.26 is a problem.
Install 1.25.0_1 and run it again. Here are grpc 1.25.0_1 install script.
```
brew install https://raw.githubusercontent.com/Homebrew/homebrew-core/35d7f485905273db8a440a9c8e7f0c2f0c8533f5/Formula/grpc.rb
```
If not resolved, you may need to reinstall the idb_companion.

**Comment by KPR7168** [comment]
> @KPR7168
> It seems that grpc 1.26 is a problem.
> Install 1.25.0_1 and run it again. Here are grpc 1.25.0_1 install script.
> 
> ```
> brew install https://raw.githubusercontent.com/Homebrew/homebrew-core/35d7f485905273db8a440a9c8e7f0c2f0c8533f5/Formula/grpc.rb
> ```
> 
> If not resolved, you may need to reinstall the idb_companion.

It works @salphaon thank you so much. 😊

**Comment by c-ryan747** [comment]
The cause of this issue is that idb dynamically links grpc when its compiled, meaning its tied to the specific version of grpc that it was built with. If your grpc version gets updated then idb will stop working.

One way to fix this is to build idb locally, rather than using the pre-build version
```
brew reinstall --build-from-source idb-companion
```

I'll take a look and see if its possible to statically link grpc, which will solve this problem for good.

**Comment by c-ryan747** [comment]
idb v1.0.12 now statically links GRPC so it should remain stable over GRPC upgrades 👍
