### ISSUE TITLE
Target doesn't conform to FBSimulatorLifecycleCommands protocol

### ISSUE THREAD

**Issue by shibupanda** [facebook/idb#580]
### Description

idb open https://facebook.com

Target doesn't conform to FBSimulatorLifecycleCommands protocol d1a080640a9066b221c6d7b215a8f6d6a7e3dffe | ios’s iPhone | Booted | iPhone 7 Plus | iOS 11.3 | arm64 | 0 | 0

### Reproduction
Run idb open https://facebook.com 

### Additional Information

* `idb` revision: [FILL THIS OUT]
Followed the document to install all today itself

**Comment by c-ryan747** [comment]
idb open can't work with devices due to restrictions imposed by Apple

**Comment by stoefln** [comment]
I don't get one thing: It looks like IDB is supposed to be the successor of WDA, but IDB is still not supporting physical devices.
Is there a roadmap, or support was just dropped?

**Comment by srapolu25** [comment]
we are also facing same issue please help

**Comment by sepsky** [comment]
I'm encountering the same issue as well. performing the `idb ui tap 200 400` returns 
```
Target doesn't conform to FBSimulatorLifecycleCommands protocol XXYYZZ  | iphone_name | Booted | iPhone 12 Pro | OS 'iOS 16.5' | arm64e
```
