### ISSUE TITLE
Many commands can't be performed on real devices

### ISSUE THREAD

**Issue by ting81** [facebook/idb#605]
We use GitHub Issues for bugs.

--- Please use this template, and delete everything above this line before submitting your issue --- 

### Description

Many commands can't work for real devices, such as open, approve, ui....

### Reproduction
 idb open xxxxxx
Target doesn't conform to FBSimulatorLifecycleCommands protocol xxx | iPhone (2) | Booted | iPhone X | iOS 13.4.1 | arm64 | 0 | 0

idb approve com.apple.Maps photos camera
Target doesn't conform to FBSimulatorSettingsCommands protocol xxxx | iPhone (2) | Booted | iPhone X | iOS 13.4.1 | arm64 | 0 | 0

idb ui describe-all
Target doesn't conform to FBSimulatorLifecycleCommands protocol xxxx | iPhone (2) | Booted | iPhone X | iOS 13.4.1 | arm64 | 0 | 0

### Additional Information

* `idb` revision: [FILL THIS OUT]

**Comment by c-ryan747** [comment]
As Apple locks down iPhones a lot more than simulators, unfortunately there are a lot of commands that have to be simulator only.

**Comment by vadimszzz** [comment]
> As Apple locks down iPhones a lot more than simulators, unfortunately there are a lot of commands that have to be simulator only.

Reopen issue. A lot of commands doesn't work. Make it work with jailbreak PLEASE
