### ISSUE TITLE
command not found: idb

### ISSUE THREAD

**Issue by sregg** [facebook/idb#615]
We use GitHub Issues for bugs.

--- Please use this template, and delete everything above this line before submitting your issue --- 

### Description

After following the installation instructions from the website or the README in GH, I can't run `idb`.

### Logs

Here's the logs to show that I installed everything but idb is not found:

```
simonreggiani@Simons-MacBook-Pro local-tennis-app % brew install idb-companion
Warning: facebook/fb/idb-companion 1.0.14 is already installed and up-to-date
To reinstall 1.0.14, run `brew reinstall idb-companion`
simonreggiani@Simons-MacBook-Pro local-tennis-app % brew reinstall idb-companion
==> Downloading https://github.com/facebook/idb/releases/download/v1.0.14/idb-companion-1.0.14.mojave.bottle.tar.gz
Already downloaded: /Users/simonreggiani/Library/Caches/Homebrew/downloads/c0f755777893a7fe69750c96d28a1394bbc64fdec58baf9a20721d5dbb271d95--idb-companion-1.0.14.mojave.bottle.tar.gz
==> Reinstalling facebook/fb/idb-companion 
==> Pouring idb-companion-1.0.14.mojave.bottle.tar.gz
==> codesign --force --sign - --timestamp=none /usr/local/Cellar/idb-companion/1.0.14/Frameworks/FBDeviceControl.framework/Versions/A/Resources/libShimulato
==> codesign --force --sign - --timestamp=none /usr/local/Cellar/idb-companion/1.0.14/Frameworks/FBSimulatorControl.framework/Versions/A/Resources/libShimul
==> codesign --force --sign - --timestamp=none /usr/local/Cellar/idb-companion/1.0.14/Frameworks/XCTestBootstrap.framework/Versions/A/Resources/libShimulato
🍺  /usr/local/Cellar/idb-companion/1.0.14: 253 files, 30.2MB
simonreggiani@Simons-MacBook-Pro local-tennis-app % pip3.8 install fb-idb
Requirement already satisfied: fb-idb in /usr/local/lib/python3.8/site-packages (1.0.12)
Requirement already satisfied: protobuf in /usr/local/Cellar/protobuf/3.12.4/libexec/lib/python3.8/site-packages (from fb-idb) (3.12.4)
Requirement already satisfied: grpclib>=0.3.2 in /usr/local/lib/python3.8/site-packages (from fb-idb) (0.3.2)
Requirement already satisfied: treelib in /usr/local/lib/python3.8/site-packages (from fb-idb) (1.6.1)
Requirement already satisfied: aiofiles in /usr/local/lib/python3.8/site-packages (from fb-idb) (0.5.0)
Requirement already satisfied: six>=1.9 in /usr/local/Cellar/protobuf/3.12.4/libexec/lib/python3.8/site-packages (from protobuf->fb-idb) (1.15.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.8/site-packages (from protobuf->fb-idb) (49.2.0)
Requirement already satisfied: multidict in /usr/local/lib/python3.8/site-packages (from grpclib>=0.3.2->fb-idb) (4.7.6)
Requirement already satisfied: h2 in /usr/local/lib/python3.8/site-packages (from grpclib>=0.3.2->fb-idb) (3.2.0)
Requirement already satisfied: future in /usr/local/lib/python3.8/site-packages (from treelib->fb-idb) (0.18.2)
Requirement already satisfied: hpack<4,>=3.0 in /usr/local/lib/python3.8/site-packages (from h2->grpclib>=0.3.2->fb-idb) (3.0.0)
Requirement already satisfied: hyperframe<6,>=5.2.0 in /usr/local/lib/python3.8/site-packages (from h2->grpclib>=0.3.2->fb-idb) (5.2.0)
simonreggiani@Simons-MacBook-Pro local-tennis-app % idb
zsh: command not found: idb
```

**Comment by c-ryan747** [comment]
When you first ran `pip3.8 install fb-idb` a message like will probably have come up:
```
  WARNING: The script idb is installed in '/Users/$USER/Library/Python/3.8/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
```
If you add this path to your PATH environment variable you should be able to run idb

**Comment by sregg** [comment]
I had to run `pip3.8 install fb-idb --user` in order to get that warning.

**Comment by acostalima** [comment]
The README implicitly suggests `idb` is added to the PATH automatically. Shouldn't the documentation be fixed...?

**Comment by oferRounds** [comment]
Hi @c-ryan747, could you share how can this be added to the PATH environment?

**Comment by nelyousfi** [comment]
I was facing the same issue. 

The solution I found was to remove idb client using 
`pip3.8 uninstall fb-idb` 

Then reinstall it using sudo:
`sudo pip3.8 install fb-idb`

The main reason why I had the problem is, without sudo permissions (or any other way to grant access) the first pip install was not able to set the necessary env variables.

**Comment by oferRounds** [comment]
Thank you @nelyousfi, worked for me also!

**Comment by haryshi** [comment]
"sudo pip3.8 install fb-idb" also solves my issue, the install doc needs to be updated.

**Comment by corasan** [comment]
> pip3.8 uninstall fb-idb

This solved it for me as well

**Comment by corasan** [comment]
> I was facing the same issue.
> 
> The solution I found was to remove idb client using
> `pip3.8 uninstall fb-idb`
> 
> Then reinstall it using sudo:
> `sudo pip3.8 install fb-idb`
> 
> The main reason why I had the problem is, without sudo permissions (or any other way to grant access) the first pip install was not able to set the necessary env variables.

This solved it for me as well

**Comment by nabilfreeman** [comment]
Thanks, also worked for me 👏

**Comment by ngtrphuong** [comment]
> I was facing the same issue.
> 
> The solution I found was to remove idb client using `pip3.8 uninstall fb-idb`
> 
> Then reinstall it using sudo: `sudo pip3.8 install fb-idb`
> 
> The main reason why I had the problem is, without sudo permissions (or any other way to grant access) the first pip install was not able to set the necessary env variables.

This also works for me!
BTW, I have to add the exact Python bin into $PATH environment variable and it works like a champ,

**Comment by hasn-ab** [comment]
sudo pip3.8 install fb-idb

> I was facing the same issue.
> 
> The solution I found was to remove idb client using `pip3.8 uninstall fb-idb`
> 
> Then reinstall it using sudo: `sudo pip3.8 install fb-idb`
> 
> The main reason why I had the problem is, without sudo permissions (or any other way to grant access) the first pip install was not able to set the necessary env variables.

this did not work for me.

What worked for me is:
`sudo -H pip3 install fb-idb`

**Comment by mxl123** [comment]
> sudo pip3.8 install fb-idb
> 
> > I was facing the same issue.
> > The solution I found was to remove idb client using `pip3.8 uninstall fb-idb`
> > Then reinstall it using sudo: `sudo pip3.8 install fb-idb`
> > The main reason why I had the problem is, without sudo permissions (or any other way to grant access) the first pip install was not able to set the necessary env variables.
> 
> this did not work for me.
> 
> What worked for me is: `sudo -H pip3 install fb-idb`

Thanks, this work for me !

**Comment by rmacd** [comment]
just to chip in here - 

literally ran every variation above, but wasn't till running `pip uninstall fb-idb && pip3 uninstall fb-idb && pip3.8 uninstall fb-idb && ... [etc]` (ie uninstalling via every possible variation of pip) before running `sudo -H pip3 install fb-idb` that I was able to get it to behave

**Comment by Jonathan0wh** [comment]
2022 end now and the doc is still the old one...

**Comment by AadityaParmar** [comment]
in my case 
it's installed in  /Users/$USER/Library/Python/3.11/bin/idb
maybe adding this as PATH will resolved

**Comment by aymather** [comment]
> 2022 end now and the doc is still the old one...

2024 and it's STILL the old one lol
