### ISSUE TITLE
Building fails: libgrpc.a and libgrpc++.a missing

### ISSUE THREAD

**Issue by iqqmuT** [facebook/idb#661]
### Description

Creating own issue from [this comment](https://github.com/facebook/idb/issues/642#issuecomment-758647799) of issue #642.

Using Xcode to build from source fails to this error:
```
clang: error: no such file or directory: '/usr/local/lib/libgrpc++.a'
clang: error: no such file or directory: '/usr/local/lib/libgrpc.a'
```

### Reproduction

Follow README instructions to build from source. gRPC was installed by `brew tap grpc/grpc && brew install grpc` but it did not provide required `libgrpc++.a` and `libgrpc.a` files.

### Additional Information

* `idb` revision: 1.0.14
* Xcode: 12.4

**Comment by wh1tecat-nya** [comment]
I have same issue and i dig it.
after [this commit](https://github.com/Homebrew/homebrew-core/commit/af9e5e24faae9ff4f23fdf9867b74371bf95b7a6#diff-2325170da0acac021ad144f5df99ce0062d90d8b489de582e8bef1e3c0ad1008), `brew install grpc` has not add `libgrpc.a` and `libgrpc++.a` files.

I try downgrade grpc to previous that commit by [step 3 of this answer method](https://stackoverflow.com/a/4158763), now has `.a` files.
and edit some Xcode build configure(ex. build target macOS version etc...), successfully build.
(but maybe something configure is wrong, i cannot connect companion...)

**Comment by iqqmuT** [comment]
Another workaround:

1. Open idb_companion project > Targets > idb_companion > Build Settings in Xcode
2. Find **Other Linker Flags**
3. Replace `/usr/local/lib/libgrpc++.a` with `/usr/local/lib/libgrpc++.dylib`
4. Replace `/usr/local/lib/libgrpc.a` with `/usr/local/lib/libgrpc.dylib`

**Comment by ZeroCho** [comment]
@iqqmuT Could you let me know where I can find idb_companion project? I wanna open it via Xcode

**Comment by iqqmuT** [comment]
@ZeroCho Clone this repository `git clone https://github.com/facebook/idb.git` and then read the instructions from [README.md](https://github.com/facebook/idb#building-from-source)

**Comment by c-ryan747** [comment]
Just changed idb to pick up grpc via cocoapods, which should improve the status quo here

**Comment by iqqmuT** [comment]
Thanks, it fixed this issue!
