### ISSUE TITLE
Can't build on XCode 12.5 -> protobuf linking issue

### ISSUE THREAD

**Issue by Hless** [facebook/idb#673]
### Description

When building idb-companion from source in XCode 12.5 it throws the following error:
```
ld: Library not loaded: /usr/local/opt/protobuf/lib/libprotoc.25.dylib
  Referenced from: /usr/local/bin/grpc_cpp_plugin
  Reason: image not found
--grpc_out: protoc-gen-grpc: Plugin killed by signal 6.
cp: /Users/boyvanderlaak/Library/Developer/Xcode/DerivedData/idb_companion-etuevgyvlohfxlhdccnkglevynxd/Build/Intermediates.noindex/idb_companion.build/Debug/idbGRPC.build/DerivedSources/*.h: No such file or directory
Command RuleScriptExecution failed with a nonzero exit code
```

It looks like the current idb master branch looks for a specific version of libprotobuf (25), but my local homebrew has already upgraded my version to 26. I'm not completely sure how to make it link versus 26.

### Reproduction
- Pull latest idb repo
- Install latest grpc via homebrew
- Open workspace in XCode 12.5
- Run idb-companion on Mac via targets

### Additional Information

* `idb` revision: D28606033

**Comment by nomi9995** [comment]
same issue

**Comment by c-ryan747** [comment]
I've just released v1.1.3 which changes grpc to be statically linked. Can you try updating to that version?

**Comment by nomi9995** [comment]
@c-ryan747 thanks it is working 🎉🎉

**Comment by iqqmuT** [comment]
I got the same error when building.

@Hless If you run `/usr/local/bin/grpc_cpp_plugin` in your terminal, does it give the same error? If yes, try to run `brew upgrade grpc`, it fixed the issue for me.

Apparently `grpc_cpp_plugin` was dynamically linked to use `libprotoc.25.dylib` but it didn't exist anymore.

**Comment by Hless** [comment]
@iqqmuT It did give me the same error, and I just now noticed that I locked my brew repo on a specific commit because of a transient dependency issue in another package. Therefore the reproduction instructions in this issue were invalid, since I wasn't on the latest grpc version.

Regardless, since grpc is now statically linked, I think we can close the issue. It's also fixed it for me 🎉
