### ISSUE TITLE
Upgrade failed from 1.1.2 to 1.1.3 with Homebrew or source build

### ISSUE THREAD

**Issue by joyy-crm** [facebook/idb#682]
### Description

**Upgrade failed from 1.1.2 to 1.1.3 with Homebrew or source build**

### Reproduction

% brew upgrade idb-companion
==> Downloading https://github.com/facebook/idb/archive/v1.1.3.tar.gz
Already downloaded: /Users/name/Library/Caches/Homebrew/downloads/91337e847405c289a70b5088cde6a6781ae05409c869724f31eb9b220799927e--idb-1.1.3.tar.gz
==> Reinstalling facebook/fb/idb-companion 
==> pod install
==> ./idb_build.sh idb_companion build /usr/local/Cellar/idb-companion/1.1.3
Last 15 lines from /Users/name/Library/Logs/Homebrew/idb-companion/02.idb_build.sh:

Touch /tmp/idb-companion-20210628-48042-1i4gpln/idb-1.1.3/build/Build/Products/Debug/FBDeviceControl.framework (in target 'FBDeviceControl' from project 'FBSimulatorControl')
    cd /tmp/idb-companion-20210628-48042-1i4gpln/idb-1.1.3
    /usr/bin/touch -c /tmp/idb-companion-20210628-48042-1i4gpln/idb-1.1.3/build/Build/Products/Debug/FBDeviceControl.framework

Touch /tmp/idb-companion-20210628-48042-1i4gpln/idb-1.1.3/build/Build/Products/Debug/FBSimulatorControl.framework (in target 'FBSimulatorControl' from project 'FBSimulatorControl')
    cd /tmp/idb-companion-20210628-48042-1i4gpln/idb-1.1.3
    /usr/bin/touch -c /tmp/idb-companion-20210628-48042-1i4gpln/idb-1.1.3/build/Build/Products/Debug/FBSimulatorControl.framework

** BUILD FAILED **

The following build commands failed:
	CompileC /tmp/idb-companion-20210628-48042-1i4gpln/idb-1.1.3/build/Build/Intermediates.noindex/idb_companion.build/Debug/idbGRPC.build/Objects-normal/x86_64/idb.pb.o /tmp/idb-companion-20210628-48042-1i4gpln/idb-1.1.3/build/Build/Intermediates.noindex/idb_companion.build/Debug/idbGRPC.build/DerivedSources/idb.pb.cc normal x86_64 c++ com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
  https://github.com/facebook/homebrew-fb/issues

**Also, when building from source:**

 % ./idb_build.sh framework build
....
 % ./idb_build.sh idb_companion build
......
note: Using new build system
note: Building targets in parallel
note: Planning build
note: Constructing build description
RuleScriptExecution /Users/name/practice/facebook_idb/master/idb/build/Build/Intermediates.noindex/idb_companion.build/Debug/idbGRPC.build/DerivedSources/idb.pb.h /Users/name/practice/facebook_idb/master/idb/build/Build/Intermediates.noindex/idb_companion.build/Debug/idbGRPC.build/DerivedSources/idb.pb.cc /Users/name/practice/facebook_idb/master/idb/build/Build/Intermediates.noindex/idb_companion.build/Debug/idbGRPC.build/DerivedSources/idb.grpc.pb.h /Users/name/practice/facebook_idb/master/idb/build/Build/Intermediates.noindex/idb_companion.build/Debug/idbGRPC.build/DerivedSources/idb.grpc.pb.cc /Users/name/practice/facebook_idb/master/idb/proto/idb.proto normal x86_64 (in target 'idbGRPC' from project 'idb_companion')
    cd /Users/name/practice/facebook_idb/master/idb
    /bin/sh -c \#\ Generate\ grpc\ code\ from\ .proto'
'PATH\=\$PATH:/opt/homebrew/bin/:/usr/local/bin'
''
'protoc\ --proto_path\=\$INPUT_FILE_DIR\ --cpp_out\=\$DERIVED_FILE_DIR\ --grpc_out\=\$DERIVED_FILE_DIR\ --plugin\=protoc-gen-grpc\=\$\(brew\ --prefix\)/bin/grpc_cpp_plugin\ \$INPUT_FILE_PATH'
''
'\#\ Copy\ headers'
'mkdir\ -p\ \$\{BUILT_PRODUCTS_DIR\}/\$\{PRODUCT_NAME\}'
'cp\ -a\ \$\{DERIVED_FILES_DIR\}/\*.h\ \$\{BUILT_PRODUCTS_DIR\}/\$\{PRODUCT_NAME\}'
'
/bin/sh: line 3: protoc: command not found
cp: /Users/name/practice/facebook_idb/master/idb/build/Build/Intermediates.noindex/idb_companion.build/Debug/idbGRPC.build/DerivedSources/*.h: No such file or directory
Command RuleScriptExecution failed with a nonzero exit code

** BUILD FAILED **

The following build commands failed:
	RuleScriptExecution /Users/name/practice/facebook_idb/master/idb/build/Build/Intermediates.noindex/idb_companion.build/Debug/idbGRPC.build/DerivedSources/idb.pb.h /Users/name/practice/facebook_idb/master/idb/build/Build/Intermediates.noindex/idb_companion.build/Debug/idbGRPC.build/DerivedSources/idb.pb.cc /Users/name/practice/facebook_idb/master/idb/build/Build/Intermediates.noindex/idb_companion.build/Debug/idbGRPC.build/DerivedSources/idb.grpc.pb.h /Users/name/practice/facebook_idb/master/idb/build/Build/Intermediates.noindex/idb_companion.build/Debug/idbGRPC.build/DerivedSources/idb.grpc.pb.cc /Users/name/practice/facebook_idb/master/idb/proto/idb.proto normal x86_64
(1 failure)

### Solution

[]

### Additional Information

* `idb` revision: [1.1.2]
* grpc revsion: [1.38.0]
* macOS : [Catalina 10.15.7]
* xcode: [12.4]

**Comment by jbardini** [comment]
Please update to `idb-companion 1.1.5` and `fb-idb 1.1.5` and re-check. As idb-companion is bottled, you could add the `--force-bottle` to your upgrade/install command.

**Comment by joyy-crm** [comment]
> Please update to `idb-companion 1.1.5` and `fb-idb 1.1.5` and re-check. As idb-companion is bottled, you could add the `--force-bottle` to your upgrade/install command.

**unfortunally, still failed when updating to 1.1.5**

==> Installing idb-companion from facebook/fb
==> Downloading https://github.com/facebook/idb/archive/v1.1.5.tar.gz
Already downloaded: /Users/crm/Library/Caches/Homebrew/downloads/626c4ce498f08179c88e9995f5f8592fe9ea0a67ccada10626a04b856e10d152--idb-1.1.5.tar.gz
==> pod install
==> ./idb_build.sh idb_companion build /usr/local/Cellar/idb-companion/1.1.5
Last 15 lines from /Users/crm/Library/Logs/Homebrew/idb-companion/02.idb_build.sh:
'
/bin/sh: line 3: protoc: command not found
cp: /tmp/idb-companion-20210719-23561-9fmis9/idb-1.1.5/build/Build/Intermediates.noindex/idb_companion.build/Debug/idbGRPC.build/DerivedSources/*.h: No such file or directory
Command RuleScriptExecution failed with a nonzero exit code

WriteAuxiliaryFile /tmp/idb-companion-20210719-23561-9fmis9/idb-1.1.5/build/Build/Intermediates.noindex/idb_companion.build/Debug/idbGRPC.build/Objects-normal/x86_64/idbGRPC.LinkFileList (in target 'idbGRPC' from project 'idb_companion')
    cd /tmp/idb-companion-20210719-23561-9fmis9/idb-1.1.5
    write-file /tmp/idb-companion-20210719-23561-9fmis9/idb-1.1.5/build/Build/Intermediates.noindex/idb_companion.build/Debug/idbGRPC.build/Objects-normal/x86_64/idbGRPC.LinkFileList

** BUILD FAILED **


The following build commands failed:
	RuleScriptExecution /tmp/idb-companion-20210719-23561-9fmis9/idb-1.1.5/build/Build/Intermediates.noindex/idb_companion.build/Debug/idbGRPC.build/DerivedSources/idb.pb.h /tmp/idb-companion-20210719-23561-9fmis9/idb-1.1.5/build/Build/Intermediates.noindex/idb_companion.build/Debug/idbGRPC.build/DerivedSources/idb.pb.cc /tmp/idb-companion-20210719-23561-9fmis9/idb-1.1.5/build/Build/Intermediates.noindex/idb_companion.build/Debug/idbGRPC.build/DerivedSources/idb.grpc.pb.h /tmp/idb-companion-20210719-23561-9fmis9/idb-1.1.5/build/Build/Intermediates.noindex/idb_companion.build/Debug/idbGRPC.build/DerivedSources/idb.grpc.pb.cc /tmp/idb-companion-20210719-23561-9fmis9/idb-1.1.5/proto/idb.proto normal x86_64
(1 failure)

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
  https://github.com/facebook/homebrew-fb/issues

**Comment by jbardini** [comment]
@joyy-crm try `brew install protobuf` before installing idb-companion. it should solve `/bin/sh: line 3: protoc: command not found`

**Comment by joyy-crm** [comment]
> @joyy-crm try `brew install protobuf` before installing idb-companion. it should solve `/bin/sh: line 3: protoc: command not found`

thanks jbardini , previous env(above logs) has alreaddy installed protobuf , but failed.
version:

% brew info protobuf
protobuf: stable 3.17.3 (bottled), HEAD
Protocol buffers (Google's data interchange format)
https://github.com/protocolbuffers/protobuf/
/usr/local/Cellar/protobuf/3.17.3 (210 files, 18MB)
  Poured from bottle on 2021-06-22 at 11:04:27
From: https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/protobuf.rb
License: BSD-3-Clause
==> Dependencies
Build: python@3.9 ✘
Required: six ✔
==> Options
--HEAD
	Install HEAD version
==> Caveats
Emacs Lisp files have been installed to:
  /usr/local/share/emacs/site-lisp/protobuf
==> Analytics
install: 93,132 (30 days), 413,576 (90 days), 1,621,204 (365 days)
install-on-request: 17,794 (30 days), 82,714 (90 days), 305,008 (365 days)
build-error: 0 (30 days)

**Comment by jbardini** [comment]
Try `brew link protobuf` to add the already installed protoc to your PATH.

**Comment by joyy-crm** [comment]
It works!  
thanks, jbardini
