### ISSUE TITLE
 what is the difference between the WDA and IDB

### ISSUE THREAD

**Issue by Jacky-LinPeng** [facebook/idb#688]
Hello, I am a beginner, who can tell me, what is the difference between the previous WDA and the current IDB? Why does Facebook not maintain WDA but re-developed IDB?
Many people who are new to this area have similar questions. Hope to get your reply to help us better understand IDB!

您好，我是初学者，谁能告诉我一下，之前的WDA和现在的IDB有啥区别？为啥facebook不维护WDA却重新又开发IDB?
我相信很多刚接触这块的人都有类似的疑问。希望得到你们的回复，帮助我们更好的了解IDB

**Comment by Jacky-LinPeng** [comment]
Can anyone tell me what idB can be used for? The official tutorial is in English, BUT I can't understand it very well, and there are almost no instructions in Chinese. I have checked the information for a few days, and so far I don't know what IDB can be used for, is it used for group control of mobile phones? Or is it for automated testing?

**Comment by Jacky-LinPeng** [comment]
Can anyone tell me, can idb be washed off? Know that idb can be used for automated testing, is it for mobile group control? Or do automated testing?

**Comment by Jacky-LinPeng** [comment]
Can anyone tell me what idb can be used for? The official tutorial is in English. I don’t understand it very clearly. There is almost no documentation in Chinese. I checked the information for a few days. So far I don’t know what idb can be used for. It is used for mobile group control. Woolen cloth? Or is it used for automated testing?

**Comment by Jacky-LinPeng** [comment]
`mac@macdeMacBook-Pro ~ % idb launch com.apple.Maps --udid 4b4eb514629e8e486b6a51e27e615566d33b8953`
`No UDID provided and there's multiple companions: [CompanionInfo(udid='4b4eb514629e8e486b6a51e27e615566d33b8953', is_local=True, address=TCPAddress(host='localhost', port=63492), metadata={}), CompanionInfo(udid='D69B5293-7CE4-4F8C-AC24-D452864925AF', is_local=True, address=TCPAddress(host='localhost', port=56025), metadata={})]`

**Comment by geekmister** [comment]
从性能、易用、扩展方面吧！我也是最近才开始研究IDB，我的邮箱geekmister.mg@gmail.com，期待互帮互助！

**Comment by Jacky-LinPeng** [comment]
> geekmister.mg@gmail.com

你是打算研究idb去做自动化测试？还是有其他用途？感觉这个利器很强，但是不知道用它能做啥? 哈哈哈哈

**Comment by geekmister** [comment]
我是做跨Windows和Mac的App，在pc端控制手机，跟自动化也类似！这个看怎么用，自动化、监控手机、手机集群都是可以的，看具体需求！

**Comment by Jacky-LinPeng** [comment]
你的这些需求，idb都支持！我是更偏向于做自动化测试，但是我发现idb的自动化测试功能不大好用，可能是我对他还不够熟悉吧，目前对`idb ui  xxx`的认知， 做自动化测试不好用！

**Comment by geekmister** [comment]
看到`idb ui xxx`就支持四种操作事件，但是我觉得还好，够用了，只是需要自己在对于idb命令进行封装，开发一些新的功能！

我现阶段就在做这块的工作...

我需要实现对命令的封装然后对用户交互这块提供底层实现能力！

你是自动化测试工程师吗？

**Comment by Jacky-LinPeng** [comment]
不是啊 我本职是做iOS研发的，最近不忙，研究了下iOS的自动化测试，然后从WDA顺藤摸瓜到IDB, 然后很纠结为啥要搞IDB,WDA结合python做自动化测试就非常好用（appium-python有封装一层），相比之下这个IDB的这个`idb ui xxx`就感觉很不好用，查找元素本来就是一个很头疼的问题，你赶紧基于idb封装一个出来方便我们使用呀 哈
