### ISSUE TITLE
Does IDB now support real-time screen stream commands?

### ISSUE THREAD

**Issue by geekmister** [facebook/idb#689]
There is no command in the IDB document to get the real-time stream of the screen, and the previous issue does not get the relevant command.

Does IDB support this command now?

**Comment by Jacky-LinPeng** [comment]
hello！
Can anyone tell me what idB can be used for? The official tutorial is in English, BUT I can't understand it very well, and there are almost no instructions in Chinese. I have checked the information for a few days, and so far I don't know what IDB can be used for, is it used for group control of mobile phones? Or is it for automated testing?

**Comment by Jacky-LinPeng** [comment]
you can try `idb video-stream --help`

**Comment by geekmister** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    hi，你好！    我也是中国人，所以就不用半生不熟的英语交流了，哈哈😄！    我是R&D Engineer，最近要做一个项目，需要采用fb-idb，也开始研究没多久，我觉得我们可以互相交流，互帮互助🤝
    
            
            
        
        我想请问下idb video-stream —help这条命令你是在哪里找到的？我没有在官方文档中找到！
    
          
        
            
    
        font{
            line-height: 1.6;
        }
    
===============================================
    
        font{
            line-height: 1.6;
        }
    
Mr GeekR&D ***@***.***+86 18201218435gk.geekkampong.cn


        
    
     
    

    On 08/6/2021 ***@***.***> wrote： 



you can try idb video-stream --help

**Comment by geekmister** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    Sorry，send the wrong person！
    
        
            
        
    
    
          
        
            
    
        font{
            line-height: 1.6;
        }
    
===============================================
    
        font{
            line-height: 1.6;
        }
    
Mr GeekR&D ***@***.***+86 18201218435gk.geekkampong.cn


        
    
     
    

    On 08/6/2021 10:06，Mr ***@***.***> wrote： 




    font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    hi，你好！    我也是中国人，所以就不用半生不熟的英语交流了，哈哈😄！    我是R&D Engineer，最近要做一个项目，需要采用fb-idb，也开始研究没多久，我觉得我们可以互相交流，互帮互助🤝
    
            
            
        
        我想请问下idb video-stream —help这条命令你是在哪里找到的？我没有在官方文档中找到！
    
          
        
            
    
        font{
            line-height: 1.6;
        }
    
===============================================
    
        font{
            line-height: 1.6;
        }
    
Mr GeekR&D ***@***.***+86 18201218435gk.geekkampong.cn


        
    
     
    

    On 08/6/2021 ***@***.***> wrote： 



you can try idb video-stream --help

**Comment by geekmister** [comment]
我在官方文档中没有找到这条命令，请问你是在哪里找到的这条命令？

**Comment by Jacky-LinPeng** [comment]
`idb`提供的能力
` add-media           Add photos/videos to the target
    approve             Approve permissions for an app
    boot                Boots a simulator (only works on mac)
    clear-keychain      Clear the targets keychain
    clone               Erases the simulator (only works on mac)
    companion           commands related to the companion
    connect             Connect to a companion
    contacts            Contacts database operations on target
    crash               Operations on crashes
    create              Creates an iOS Simulator
    daemon              This command is deprecated. the idb daemon is not used anymore.
    debugserver         debugserver interactions
    delete              Deletes (only works on mac)
    delete-all          Deletes all simulators (only works on mac)
    describe            Describes the Target
    disconnect          Disconnect a companion
    dsym                dsym commands
    dylib               dylib commands
    erase               Erases the simulator (only works on mac)
    file                File operations on target
    focus               Brings the simulator window to front
    framework           framework commands
    get                 Gets a value from the target
    install             Install an application
    instruments         Run instruments on the device
    kill                Kill the idb daemon
    launch              Launch an application. Any environment variables of the form IDB_X
                         will be passed through with the IDB_ prefix removed.
    list                Lists values from the target
    list-apps           List the installed apps
    list-targets        List the connected targets
    log                 Obtain logs from the target
    open                Open a URL
    record              Record what the screen is doing
    screenshot          Take a Screenshot of the Target
    set                 Sets a preference on the target
    set-location        Set a simulator's location
    shell               Interactive shell
    shutdown            Shuts the simulator down (only works on mac)
    terminate           Terminate a running application
    ui                  UI interactions on target
    uninstall           Uninstall an application
    video (record-video)
                        Record the target's screen to a mp4 video file
    video-stream        Stream raw H264 from the target
    xctest              Operations with xctest on target
    xctrace             Run xctrace commands
`

**Comment by Jacky-LinPeng** [comment]
<img width="678" alt="image" src="https://user-images.githubusercontent.com/15797691/128450124-15ebd419-7128-496d-8311-f082041e2fbc.png">

**Comment by geekmister** [comment]
请问你发的截图是在哪里找到的？为什么我看到的文档跟你的不一样？你是在[idb doc](https://fbidb.io/docs/)这个站点里找到的吗？

**Comment by geekmister** [comment]
你截图里的内容是不是在源代码里找到的？我不懂iOS开发，方便指点一下，截图里的内容是在哪找到的吗？

**Comment by Jacky-LinPeng** [comment]
`idb --help`

**Comment by geekmister** [comment]
尴尬了...
谢谢！
