### ISSUE TITLE
idb launch com.apple.Maps get error

### ISSUE THREAD

**Issue by Jacky-LinPeng** [facebook/idb#690]
We use GitHub Issues for bugs.

### Description

1.`idb list-targets`  work fine
2.`idb boot UDID` work fine too
3.`idb launch com.apple.Maps --UDID` get error

error:
`mac@macdeMacBook-Pro ~ % idb launch com.apple.Maps --udid DA7FBB6E-CE17-43D0-A953-9F47E7759078
No UDID provided and there's multiple companions: [CompanionInfo(udid='4b4eb514629e8e486b6a51e27e615566d33b8953', is_local=True, address=TCPAddress(host='localhost', port=63862), metadata={}), CompanionInfo(udid='D69B5293-7CE4-4F8C-AC24-D452864925AF', is_local=True, address=TCPAddress(host='localhost', port=56025), metadata={}), CompanionInfo(udid='DA7FBB6E-CE17-43D0-A953-9F47E7759078', is_local=True, address=TCPAddress(host='localhost', port=64125), metadata={})]`
### Reproduction

Following the tutorial, it is difficult to continue...

**Comment by jbardini** [comment]
The bundle id needs to be the last parameter (see `idb launch --help`). Try: `idb launch --udid <your_sim_uuid_here> com.apple.Maps`

**Comment by Jacky-LinPeng** [comment]
> The bundle id needs to be the last parameter (see `idb launch --help`). Try: `idb launch --udid <your_sim_uuid_here> com.apple.Maps`

oh...... Thanks !!!!!!
