### ISSUE TITLE
Cannot install idb

### ISSUE THREAD

**Issue by Stophface** [facebook/idb#751]
### Description

I tried to install the idb-companion via

`$ brew install idb-companion`

I got the following error Message:

> Last 15 lines from /Users/macosx/Library/Logs/Homebrew/idb-companion/02.idb_build.sh:
    cd /tmp/idb-companion-20211226-17909-15qgl50/idb-1.1.5
    export LANG\=en_US.US-ASCII
    clang -x objective-c -target x86_64-apple-macos10.14 -fmessage-length\=0 -fdiagnostics-show-note-include-stack -fmacro-backtrace-limit\=0 -std\=gnu99 -fobjc-arc -fmodules -gmodules -fmodules-cache-path\=/tmp/idb-companion-20211226-17909-15qgl50/idb-1.1.5/build/ModuleCache.noind
> ...
> ... 
> ** BUILD FAILED **
> The following build commands failed:
	RuleScriptExecution /tmp/idb-companion-20211226-17909-15qgl50/idb-1.1.5/build/Build/Intermediates.noindex/idb_companion.build/Debug/idbGRPC.build/DerivedSources/idb.pb.h /tmp/idb-companion-20211226-17909-15qgl50/idb-1.1.5/build/Build/Intermediates.noindex/idb_companion.build/Debug/idbGRPC.build/DerivedSources/idb.pb.cc /tmp/idb-companion-20211226-17909-15qgl50/idb-1.1.5/build/Build/Intermediates.noindex/idb_companion.build/Debug/idbGRPC.build/DerivedSources/idb.grpc.pb.h /tmp/idb-companion-20211226-17909-15qgl50/idb-1.1.5/build/Build/Intermediates.noindex/idb_companion.build/Debug/idbGRPC.build/DerivedSources/idb.grpc.pb.cc /tmp/idb-companion-20211226-17909-15qgl50/idb-1.1.5/proto/idb.proto normal x86_64
(1 failure)

Any ideas?

**Comment by realesh** [comment]
also having the same issue
manually built the package on 1.1.6 (latest) & 1.1.5 didn't work
aprreciate if anyone can help 🙏

**Comment by jbardini** [comment]
Please try again with v1.1.7 as the project dependencies have been fixed.

I'm closing this, but feel free to reopen if the issue persists.
