### ISSUE TITLE
Failed to install Idb-Companion on Mac(v11.4)

### ISSUE THREAD

**Issue by bravepiper** [facebook/idb#757]
I tried to install idb-conpanion with $ brew install idb-companion, but failed, the detailed information is as following, any idea for this? appreciated for help.

Mac OS version is v11.4.

******************************************************

Last 15 lines from /Users/jackyx/Library/Logs/Homebrew/idb-companion/02.idb_build.sh:
    cd /tmp/idb-companion-20220117-6606-195rl9r/idb-1.1.6
    export LANG\=en_US.US-ASCII
    clang -x objective-c -target x86_64-apple-macos10.14 -fmessage-length\=0 -fdiagnostics-show-note-include-stack -fmacro-backtrace-limit\=0 -std\=gnu99 -fobjc-arc -fmodules -gmodules -fmodules-cache-path\=/tmp/idb-companion-20220117-6606-195rl9r/idb-1.1.6/build/ModuleCache.noindex -fmodules-prune-interval\=86400 -fmodules-prune-after\=345600 -fbuild-session-file\=/tmp/idb-companion-20220117-6606-195rl9r/idb-1.1.6/build/ModuleCache.noindex/Session.modulevalidation -fmodules-validate-once-per-build-session -Wnon-modular-include-in-framework-module -Werror\=non-modular-include-in-framework-module -fmodule-name\=FBSimulatorControl -Wno-trigraphs -fpascal-strings -O0 -fno-common -Werror -Werror\=incompatible-pointer-types -Werror\=implicit-function-declaration -Wmissing-field-initializers -Wmissing-prototypes -Wdocumentation -Wunreachable-code -Wno-implicit-atomic-properties -Werror\=deprecated-objc-isa-usage -Wno-objc-interface-ivars -Werror\=objc-root-class -Wno-arc-repeated-use-of-weak -Wimplicit-retain-self -Wmissing-braces -Wparentheses -Wswitch -Wunused-function -Wunused-label -Wno-unused-parameter -Wunused-variable -Wunused-value -Wempty-body -Wuninitialized -Wconditional-uninitialized -Wunknown-pragmas -Wshadow -Wfour-char-constants -Wconversion -Wconstant-conversion -Wint-conversion -Wbool-conversion -Wenum-conversion -Wfloat-conversion -Wnon-literal-null-conversion -Wobjc-literal-conversion -Wsign-compare -Wshorten-64-to-32 -Wpointer-sign -Wnewline-eof -Wno-selector -Wno-strict-selector-match -Wundeclared-selector -Wdeprecated-implementations -DDEBUG\=1 -DOBJC_OLD_DISPATCH_PROTOTYPES\=0 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.1.sdk -fasm-blocks -fstrict-aliasing -Wprotocol -Wdeprecated-declarations -g -Wsign-conversion -Winfinite-recursion -Wcomma -Wblock-capture-autoreleasing -Wstrict-prototypes -Wno-semicolon-before-method-body -index-store-path /tmp/idb-companion-20220117-6606-195rl9r/idb-1.1.6/build/Index/DataStore -iquote /tmp/idb-companion-20220117-6606-195rl9r/idb-1.1.6/build/Build/Intermediates.noindex/FBSimulatorControl.build/Debug/FBSimulatorControl.build/FBSimulatorControl-generated-files.hmap -I/tmp/idb-companion-20220117-6606-195rl9r/idb-1.1.6/build/Build/Intermediates.noindex/FBSimulatorControl.build/Debug/FBSimulatorControl.build/FBSimulatorControl-own-target-headers.hmap -I/tmp/idb-companion-20220117-6606-195rl9r/idb-1.1.6/build/Build/Intermediates.noindex/FBSimulatorControl.build/Debug/FBSimulatorControl.build/FBSimulatorControl-all-non-framework-target-headers.hmap -ivfsoverlay /tmp/idb-companion-20220117-6606-195rl9r/idb-1.1.6/build/Build/Intermediates.noindex/FBSimulatorControl.build/Debug/FBSimulatorControl.build/all-product-headers.yaml -iquote /tmp/idb-companion-20220117-6606-195rl9r/idb-1.1.6/build/Build/Intermediates.noindex/FBSimulatorControl.build/Debug/FBSimulatorControl.build/FBSimulatorControl-project-headers.hmap -I/tmp/idb-companion-20220117-6606-195rl9r/idb-1.1.6/build/Build/Products/Debug/include -I/tmp/idb-companion-20220117-6606-195rl9r/idb-1.1.6/PrivateHeaders -I/tmp/idb-companion-20220117-6606-195rl9r/idb-1.1.6/build/Build/Intermediates.noindex/FBSimulatorControl.build/Debug/FBSimulatorControl.build/DerivedSources-normal/x86_64 -I/tmp/idb-companion-20220117-6606-195rl9r/idb-1.1.6/build/Build/Intermediates.noindex/FBSimulatorControl.build/Debug/FBSimulatorControl.build/DerivedSources/x86_64 -I/tmp/idb-companion-20220117-6606-195rl9r/idb-1.1.6/build/Build/Intermediates.noindex/FBSimulatorControl.build/Debug/FBSimulatorControl.build/DerivedSources -F/tmp/idb-companion-20220117-6606-195rl9r/idb-1.1.6/build/Build/Products/Debug -F/Applications/Xcode.app/Contents/Frameworks -F/Applications/Xcode.app/Contents/PlugIns -F/Applications/Xcode.app/Contents/OtherFrameworks -F/Applications/Xcode.app/Contents/SharedFrameworks -F/Applications/Xcode.app/Contents/Developer/Library/PrivateFrameworks -F/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.1.sdk/System/Library/PrivateFrameworks -F/Library/Developer/PrivateFrameworks -MMD -MT dependencies -MF /tmp/idb-companion-20220117-6606-195rl9r/idb-1.1.6/build/Build/Intermediates.noindex/FBSimulatorControl.build/Debug/FBSimulatorControl.build/Objects-normal/x86_64/FBSimulatorHID.d --serialize-diagnostics /tmp/idb-companion-20220117-6606-195rl9r/idb-1.1.6/build/Build/Intermediates.noindex/FBSimulatorControl.build/Debug/FBSimulatorControl.build/Objects-normal/x86_64/FBSimulatorHID.dia -c /tmp/idb-companion-20220117-6606-195rl9r/idb-1.1.6/FBSimulatorControl/HID/FBSimulatorHID.m -o /tmp/idb-companion-20220117-6606-195rl9r/idb-1.1.6/build/Build/Intermediates.noindex/FBSimulatorControl.build/Debug/FBSimulatorControl.build/Objects-normal/x86_64/FBSimulatorHID.o

CompileC /tmp/idb-companion-20220117-6606-195rl9r/idb-1.1.6/build/Build/Intermediates.noindex/FBSimulatorControl.build/Debug/FBSimulatorControl.build/Objects-normal/x86_64/FBSimulatorFileCommands.o /tmp/idb-companion-20220117-6606-195rl9r/idb-1.1.6/FBSimulatorControl/Commands/FBSimulatorFileCommands.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler (in target 'FBSimulatorControl' from project 'FBSimulatorControl')
    cd /tmp/idb-companion-20220117-6606-195rl9r/idb-1.1.6
    export LANG\=en_US.US-ASCII
    clang -x objective-c -target x86_64-apple-macos10.14 -fmessage-length\=0 -fdiagnostics-show-note-include-stack -fmacro-backtrace-limit\=0 -std\=gnu99 -fobjc-arc -fmodules -gmodules -fmodules-cache-path\=/tmp/idb-companion-20220117-6606-195rl9r/idb-1.1.6/build/ModuleCache.noindex -fmodules-prune-interval\=86400 -fmodules-prune-after\=345600 -fbuild-session-file\=/tmp/idb-companion-20220117-6606-195rl9r/idb-1.1.6/build/ModuleCache.noindex/Session.modulevalidation -fmodules-validate-once-per-build-session -Wnon-modular-include-in-framework-module -Werror\=non-modular-include-in-framework-module -fmodule-name\=FBSimulatorControl -Wno-trigraphs -fpascal-strings -O0 -fno-common -Werror -Werror\=incompatible-pointer-types -Werror\=implicit-function-declaration -Wmissing-field-initializers -Wmissing-prototypes -Wdocumentation -Wunreachable-code -Wno-implicit-atomic-properties -Werror\=deprecated-objc-isa-usage -Wno-objc-interface-ivars -Werror\=objc-root-class -Wno-arc-repeated-use-of-weak -Wimplicit-retain-self -Wmissing-braces -Wparentheses -Wswitch -Wunused-function -Wunused-label -Wno-unused-parameter -Wunused-variable -Wunused-value -Wempty-body -Wuninitialized -Wconditional-uninitialized -Wunknown-pragmas -Wshadow -Wfour-char-constants -Wconversion -Wconstant-conversion -Wint-conversion -Wbool-conversion -Wenum-conversion -Wfloat-conversion -Wnon-literal-null-conversion -Wobjc-literal-conversion -Wsign-compare -Wshorten-64-to-32 -Wpointer-sign -Wnewline-eof -Wno-selector -Wno-strict-selector-match -Wundeclared-selector -Wdeprecated-implementations -DDEBUG\=1 -DOBJC_OLD_DISPATCH_PROTOTYPES\=0 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.1.sdk -fasm-blocks -fstrict-aliasing -Wprotocol -Wdeprecated-declarations -g -Wsign-conversion -Winfinite-recursion -Wcomma -Wblock-capture-autoreleasing -Wstrict-prototypes -Wno-semicolon-before-method-body -index-store-path /tmp/idb-companion-20220117-6606-195rl9r/idb-1.1.6/build/Index/DataStore -iquote /tmp/idb-companion-20220117-6606-195rl9r/idb-1.1.6/build/Build/Intermediates.noindex/FBSimulatorControl.build/Debug/FBSimulatorControl.build/FBSimulatorControl-generated-files.hmap -I/tmp/idb-companion-20220117-6606-195rl9r/idb-1.1.6/build/Build/Intermediates.noindex/FBSimulatorControl.build/Debug/FBSimulatorControl.build/FBSimulatorControl-own-target-headers.hmap -I/tmp/idb-companion-20220117-6606-195rl9r/idb-1.1.6/build/Build/Intermediates.noindex/FBSimulatorControl.build/Debug/FBSimulatorControl.build/FBSimulatorControl-all-non-framework-target-headers.hmap -ivfsoverlay /tmp/idb-companion-20220117-6606-195rl9r/idb-1.1.6/build/Build/Intermediates.noindex/FBSimulatorControl.build/Debug/FBSimulatorControl.build/all-product-headers.yaml -iquote /tmp/idb-companion-20220117-6606-195rl9r/idb-1.1.6/build/Build/Intermediates.noindex/FBSimulatorControl.build/Debug/FBSimulatorControl.build/FBSimulatorControl-project-headers.hmap -I/tmp/idb-companion-20220117-6606-195rl9r/idb-1.1.6/build/Build/Products/Debug/include -I/tmp/idb-companion-20220117-6606-195rl9r/idb-1.1.6/PrivateHeaders -I/tmp/idb-companion-20220117-6606-195rl9r/idb-1.1.6/build/Build/Intermediates.noindex/FBSimulatorControl.build/Debug/FBSimulatorControl.build/DerivedSources-normal/x86_64 -I/tmp/idb-companion-20220117-6606-195rl9r/idb-1.1.6/build/Build/Intermediates.noindex/FBSimulatorControl.build/Debug/FBSimulatorControl.build/DerivedSources/x86_64 -I/tmp/idb-companion-20220117-6606-195rl9r/idb-1.1.6/build/Build/Intermediates.noindex/FBSimulatorControl.build/Debug/FBSimulatorControl.build/DerivedSources -F/tmp/idb-companion-20220117-6606-195rl9r/idb-1.1.6/build/Build/Products/Debug -F/Applications/Xcode.app/Contents/Frameworks -F/Applications/Xcode.app/Contents/PlugIns -F/Applications/Xcode.app/Contents/OtherFrameworks -F/Applications/Xcode.app/Contents/SharedFrameworks -F/Applications/Xcode.app/Contents/Developer/Library/PrivateFrameworks -F/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.1.sdk/System/Library/PrivateFrameworks -F/Library/Developer/PrivateFrameworks -MMD -MT dependencies -MF /tmp/idb-companion-20220117-6606-195rl9r/idb-1.1.6/build/Build/Intermediates.noindex/FBSimulatorControl.build/Debug/FBSimulatorControl.build/Objects-normal/x86_64/FBSimulatorFileCommands.d --serialize-diagnostics /tmp/idb-companion-20220117-6606-195rl9r/idb-1.1.6/build/Build/Intermediates.noindex/FBSimulatorControl.build/Debug/FBSimulatorControl.build/Objects-normal/x86_64/FBSimulatorFileCommands.dia -c /tmp/idb-companion-20220117-6606-195rl9r/idb-1.1.6/FBSimulatorControl/Commands/FBSimulatorFileCommands.m -o /tmp/idb-companion-20220117-6606-195rl9r/idb-1.1.6/build/Build/Intermediates.noindex/FBSimulatorControl.build/Debug/FBSimulatorControl.build/Objects-normal/x86_64/FBSimulatorFileCommands.o

** BUILD FAILED **

The following build commands failed:
	CompileC /tmp/idb-companion-20220117-6606-195rl9r/idb-1.1.6/build/Build/Intermediates.noindex/idb_companion.build/Debug/idbGRPC.build/Objects-normal/x86_64/idb.pb.o /tmp/idb-companion-20220117-6606-195rl9r/idb-1.1.6/build/Build/Intermediates.noindex/idb_companion.build/Debug/idbGRPC.build/DerivedSources/idb.pb.cc normal x86_64 c++ com.apple.compilers.llvm.clang.1_0.compiler (in target 'idbGRPC' from project 'idb_companion')
(1 failure)
********

**Comment by liamjones** [comment]
Also happening on macOS 11.6.2. The output from brew install doesn't reveal enough unfortunately but by digging into /Users/[name]/Library/Logs/Homebrew/idb-companion/02.idb_build.sh I can see this which looks relevant:

```
/tmp/idb-companion-20220119-89424-k3lq5e/idb-1.1.6/build/Build/Intermediates.noindex/idb_companion.build/Debug/idbGRPC.build/DerivedSources/idb.pb.h:12:2: error: This file was generated by a newer version of protoc which is
/tmp/idb-companion-20220119-89424-k3lq5e/idb-1.1.6/build/Build/Intermediates.noindex/idb_companion.build/Debug/idbGRPC.build/DerivedSources/idb.pb.h:13:2: error: incompatible with your Protocol Buffer headers. Please update
/tmp/idb-companion-20220119-89424-k3lq5e/idb-1.1.6/build/Build/Intermediates.noindex/idb_companion.build/Debug/idbGRPC.build/DerivedSources/idb.pb.h:14:2: error: your headers.
```

**Comment by jbardini** [comment]
Please try again with v1.1.7 as the project dependencies have been fixed.

I'm closing this, but feel free to reopen if the issue persists.
