### ISSUE TITLE
idb list-targets return "No targets available"

### ISSUE THREAD

**Issue by YifeiZhou02** [facebook/idb#856]
--- Please use this template, and delete everything above this line before submitting your issue --- 

### Description

I used mac mini 2023 Apple M2 with Sonoma 14.2.1 and I have vscode installed. Simulator is able to run locally. I followed the guide to install idb-companion and idb, the installation was smooth. When I tried "idb list-targets", it returns "No targets available" while the Simulator does have a few simulator.

### Reproduction

[FILL THIS OUT: How can we reproduce the bug? Provide logs for the client and server.]

**Comment by answer-huang** [comment]
idb list-targets --log DEBUG

you will find solution in the logs.

**Comment by YifeiZhou02** [comment]
it solves my problem, thanks!
